/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.Login_controller;
import Controller.MemberManage_controller;
import model.DBConnection;

/**
 *
 * @author 20183150 김부성
 * 클래스 사용 용도
 * 로그인과 회원가입의 화면이다.
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        panelClear();
        LOGIN_P.setVisible(true);
        DBConnection.getInstance().Initailize();
    }
    
    public void panelClear(){ //패널들 전부 안보이게하는 함수
        LOGIN_P.setVisible(false);
        SIGN_UP_P.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SIGN_UP_P = new javax.swing.JPanel();
        NUMBER = new javax.swing.JTextField();
        NAME = new javax.swing.JTextField();
        PHONE = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SIGN_PW = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EMAIL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SIGN_UP_BTN = new javax.swing.JButton();
        CANCEL_BTN = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        EMAIL_LIST = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        PHONE1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        PHONE2 = new javax.swing.JTextField();
        LOGIN_P = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ID_FIELD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PW_FIELD = new javax.swing.JPasswordField();
        LOGIN_BTN = new javax.swing.JButton();
        SIGN_UP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("실습실 관리 시스템");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SIGN_UP_P.setBackground(new java.awt.Color(255, 255, 255));
        SIGN_UP_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        SIGN_UP_P.add(NUMBER, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 89, 25));
        SIGN_UP_P.add(NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 89, 25));

        PHONE.setEditable(false);
        PHONE.setText("010");
        SIGN_UP_P.add(PHONE, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 40, 25));

        jLabel3.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel3.setText("회원가입");
        SIGN_UP_P.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));
        SIGN_UP_P.add(SIGN_PW, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 150, 25));

        jLabel5.setText("학번");
        SIGN_UP_P.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        jLabel6.setText("이름");
        SIGN_UP_P.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));
        SIGN_UP_P.add(EMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 100, 25));

        jLabel7.setText("비밀번호");
        SIGN_UP_P.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabel8.setText("전화번호");
        SIGN_UP_P.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        jLabel9.setText("이메일");
        SIGN_UP_P.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        SIGN_UP_BTN.setText("가입하기");
        SIGN_UP_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIGN_UP_BTNActionPerformed(evt);
            }
        });
        SIGN_UP_P.add(SIGN_UP_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        CANCEL_BTN.setText("취소하기");
        CANCEL_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCEL_BTNActionPerformed(evt);
            }
        });
        SIGN_UP_P.add(CANCEL_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        jLabel10.setFont(new java.awt.Font("굴림", 0, 10)); // NOI18N
        jLabel10.setText("(' - ' 미포함)");
        SIGN_UP_P.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel11.setText("@");
        SIGN_UP_P.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        EMAIL_LIST.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "naver.com", "gmail.com", "deu.ac.kr", "daum.net" }));
        SIGN_UP_P.add(EMAIL_LIST, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 100, -1));

        jLabel12.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel12.setText("-");
        SIGN_UP_P.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, 10));
        SIGN_UP_P.add(PHONE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 65, 25));

        jLabel13.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel13.setText("-");
        SIGN_UP_P.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 130, -1, 10));
        SIGN_UP_P.add(PHONE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 120, 65, 25));

        getContentPane().add(SIGN_UP_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 360));

        LOGIN_P.setBackground(new java.awt.Color(255, 255, 255));
        LOGIN_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("맑은 고딕", 1, 36)); // NOI18N
        jLabel4.setText("S.M.P");
        LOGIN_P.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 82, -1, -1));

        ID_FIELD.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        LOGIN_P.add(ID_FIELD, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 187, 30));

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        jLabel1.setText("ID : ");
        LOGIN_P.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 141, -1, -1));

        jLabel2.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        jLabel2.setText("PW : ");
        LOGIN_P.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 195, -1, -1));

        PW_FIELD.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        LOGIN_P.add(PW_FIELD, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 187, 30));

        LOGIN_BTN.setBackground(new java.awt.Color(255, 255, 255));
        LOGIN_BTN.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        LOGIN_BTN.setText("로그인");
        LOGIN_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGIN_BTNActionPerformed(evt);
            }
        });
        LOGIN_P.add(LOGIN_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 87, 30));

        SIGN_UP.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        SIGN_UP.setText("회원가입하기");
        SIGN_UP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SIGN_UPMouseClicked(evt);
            }
        });
        LOGIN_P.add(SIGN_UP, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 250, -1, -1));

        getContentPane().add(LOGIN_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SIGN_UPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIGN_UPMouseClicked
        // 회원가입화면으로 이동
        panelClear();
        SIGN_UP_P.setVisible(true);
    }//GEN-LAST:event_SIGN_UPMouseClicked

    private void CANCEL_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCEL_BTNActionPerformed
        // 회원가입 취소
        panelClear();
        LOGIN_P.setVisible(true);
    }//GEN-LAST:event_CANCEL_BTNActionPerformed

    private void SIGN_UP_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIGN_UP_BTNActionPerformed
        // 회원가입 하기
       MemberManage_controller signup = new MemberManage_controller(this);
       signup.singUp();
    }//GEN-LAST:event_SIGN_UP_BTNActionPerformed

    private void LOGIN_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGIN_BTNActionPerformed
        // 로그인 버튼
        Login_controller login = new Login_controller(this);
        login.login();
    }//GEN-LAST:event_LOGIN_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CANCEL_BTN;
    public javax.swing.JTextField EMAIL;
    public javax.swing.JComboBox<String> EMAIL_LIST;
    public javax.swing.JTextField ID_FIELD;
    private javax.swing.JButton LOGIN_BTN;
    public javax.swing.JPanel LOGIN_P;
    public javax.swing.JTextField NAME;
    public javax.swing.JTextField NUMBER;
    public javax.swing.JTextField PHONE;
    public javax.swing.JTextField PHONE1;
    public javax.swing.JTextField PHONE2;
    public javax.swing.JPasswordField PW_FIELD;
    public javax.swing.JPasswordField SIGN_PW;
    private javax.swing.JLabel SIGN_UP;
    private javax.swing.JButton SIGN_UP_BTN;
    private javax.swing.JPanel SIGN_UP_P;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
