/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author 20183150 김부성
 * 클래스 사용 용도 : 관리자 화면 제작 클래스
 * 
 */
public class Manager_Main extends javax.swing.JFrame {

    public Manager_Main() {
        initComponents();
        panelClear();
        M_NOTICE_P.setVisible(true); //초기 메인 화면 출력
    }
    
    public void panelClear(){ // 모든 패널을 지우는 함수
        M_NOTICE_P.setVisible(false);
        STU_MANAGEMENT_P.setVisible(false);
        INPUT_TIME_P.setVisible(false);
        RESERVATION_LIST_P.setVisible(false);
    }
    public void setaddActionListener(ActionListener listener) {
       APPROVAL_ALL_BTN.addActionListener(listener); // 일괄 승인 버튼 리스너
       APPROVAL_BTN.addActionListener(listener); // 승인하기 버튼 리스너
       SPECIAL_SELECT_DAY_BTN.addActionListener(listener);//특강 시간표 입력
       CLASS_SELECT_DAY_BTN.addActionListener(listener);//강의 시간표 입력
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        USING_NOW_LAB = new javax.swing.ButtonGroup();
        UNDER_P = new javax.swing.JPanel();
        MAIN_P = new javax.swing.JPanel();
        M_MENU_P = new javax.swing.JPanel();
        M_MENU2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        M_MENU3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        M_MENU4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        M_MENU1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        STU_MANAGEMENT_P = new javax.swing.JPanel();
        STU_M_P = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        STU_LIST = new javax.swing.JLabel();
        STU_TOKEN = new javax.swing.JLabel();
        STU_LIST_P = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        STU_LIST_T = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        STU_TOKEN_P = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        M_NOTICE_P = new javax.swing.JPanel();
        NOTICE_M_P = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        NOTICE_L = new javax.swing.JLabel();
        Declaration_L = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        NOTICE_LIST = new javax.swing.JTable();
        NOTICE_TITLE = new javax.swing.JLabel();
        WRITE = new javax.swing.JLabel();
        CHANGE = new javax.swing.JLabel();
        DELETE = new javax.swing.JLabel();
        RESERVATION_LIST_P = new javax.swing.JPanel();
        RESERVATION_M_P = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        REQUEST_RESER = new javax.swing.JLabel();
        USING_HISTORY = new javax.swing.JLabel();
        USING_NOW = new javax.swing.JLabel();
        USING_NOW_P = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        USING_915 = new javax.swing.JRadioButton();
        USING_916 = new javax.swing.JRadioButton();
        USING_918 = new javax.swing.JRadioButton();
        USING_911 = new javax.swing.JRadioButton();
        NOW_USING_PANEL1 = new javax.swing.JPanel();
        NOW_USING_PANEL2 = new javax.swing.JPanel();
        REQUEST_RESER_P = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        REQUEST_TABLE = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        APPROVAL_ALL_BTN = new javax.swing.JButton();
        APPROVAL_BTN = new javax.swing.JButton();
        USING_HISTORY_P = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        HISTORY_TALBE = new javax.swing.JTable();
        INPUT_TIME_P = new javax.swing.JPanel();
        INPUT_M_P = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        INPUT_CLASS = new javax.swing.JLabel();
        INPUT_SPECIAL = new javax.swing.JLabel();
        INPUT_CLASS_TIME_P = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        CLASS_LAB_915 = new javax.swing.JRadioButton();
        CLASS_LAB_916 = new javax.swing.JRadioButton();
        CLASS_LAB_918 = new javax.swing.JRadioButton();
        CLASS_LAB_911 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        CLASS_START_TIME = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        CLASS_END_TIME = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        CLASS_date = new javax.swing.JComboBox<>();
        CLASS_SELECT_DAY_BTN = new javax.swing.JButton();
        INPUT_SPECIAL_TIME_P = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        SPECIAL_YEAR = new javax.swing.JComboBox<>();
        SPECIAL_LAB_918 = new javax.swing.JRadioButton();
        SPECIAL_SELECT_DAY_BTN = new javax.swing.JButton();
        SPECIAL_LAB_911 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        SPECIAL_START_TIME = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        SPECIAL_END_TIME = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        SPECIAL_LAB_915 = new javax.swing.JRadioButton();
        jSeparator7 = new javax.swing.JSeparator();
        SPECIAL_LAB_916 = new javax.swing.JRadioButton();
        SPECIAL_MONTH = new javax.swing.JComboBox<>();
        SPECIAL_DATE = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TITLE_P = new javax.swing.JPanel();
        TITLE = new javax.swing.JLabel();
        LOGOUT = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SNAME = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("실습실 관리 시스템");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UNDER_P.setMinimumSize(new java.awt.Dimension(814, 590));
        UNDER_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MAIN_P.setBackground(new java.awt.Color(255, 255, 255));
        MAIN_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        M_MENU_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        M_MENU2.setBackground(new java.awt.Color(255, 255, 255));
        M_MENU2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        M_MENU2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        M_MENU2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        M_MENU2.setPreferredSize(new java.awt.Dimension(204, 3));
        M_MENU2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_MENU2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                M_MENU2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                M_MENU2MouseExited(evt);
            }
        });
        M_MENU2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("예약 내역 조회");
        M_MENU2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 34));

        M_MENU_P.add(M_MENU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 0, 204, 34));

        M_MENU3.setBackground(new java.awt.Color(255, 255, 255));
        M_MENU3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        M_MENU3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        M_MENU3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_MENU3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                M_MENU3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                M_MENU3MouseExited(evt);
            }
        });
        M_MENU3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("실습실 시간표 입력 ");
        M_MENU3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 34));

        M_MENU_P.add(M_MENU3, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 0, 204, 34));

        M_MENU4.setBackground(new java.awt.Color(255, 255, 255));
        M_MENU4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        M_MENU4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        M_MENU4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_MENU4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                M_MENU4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                M_MENU4MouseExited(evt);
            }
        });
        M_MENU4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("게시판");
        M_MENU4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 34));

        M_MENU_P.add(M_MENU4, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 0, 204, 34));

        M_MENU1.setBackground(new java.awt.Color(255, 255, 255));
        M_MENU1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        M_MENU1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        M_MENU1.setPreferredSize(new java.awt.Dimension(204, 34));
        M_MENU1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_MENU1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                M_MENU1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                M_MENU1MouseExited(evt);
            }
        });
        M_MENU1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText(" 학생 명단 관리");
        M_MENU1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 34));

        M_MENU_P.add(M_MENU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 204, 34));

        MAIN_P.add(M_MENU_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        STU_MANAGEMENT_P.setBackground(new java.awt.Color(255, 255, 255));
        STU_MANAGEMENT_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        STU_M_P.setPreferredSize(new java.awt.Dimension(100, 426));

        jLabel7.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel7.setText("MENU");

        STU_LIST.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        STU_LIST.setText("학생 명단 관리");
        STU_LIST.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        STU_LIST.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                STU_LISTMouseClicked(evt);
            }
        });

        STU_TOKEN.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        STU_TOKEN.setText("토큰 관리");
        STU_TOKEN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        STU_TOKEN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                STU_TOKENMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout STU_M_PLayout = new javax.swing.GroupLayout(STU_M_P);
        STU_M_P.setLayout(STU_M_PLayout);
        STU_M_PLayout.setHorizontalGroup(
            STU_M_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STU_M_PLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(STU_M_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(STU_TOKEN)
                    .addComponent(jLabel7)
                    .addComponent(STU_LIST)
                    .addComponent(jSeparator2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        STU_M_PLayout.setVerticalGroup(
            STU_M_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STU_M_PLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(STU_LIST)
                .addGap(18, 18, 18)
                .addComponent(STU_TOKEN)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        STU_MANAGEMENT_P.add(STU_M_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 426));

        STU_LIST_P.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel9.setText("학생 명단");

        STU_LIST_T.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "학번", "이름", "전화번호", "이메일", "승인 여부"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        STU_LIST_T.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        STU_LIST_T.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(STU_LIST_T);

        jButton1.setText("삭제");

        jButton2.setText("정보 수정");

        javax.swing.GroupLayout STU_LIST_PLayout = new javax.swing.GroupLayout(STU_LIST_P);
        STU_LIST_P.setLayout(STU_LIST_PLayout);
        STU_LIST_PLayout.setHorizontalGroup(
            STU_LIST_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, STU_LIST_PLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(STU_LIST_PLayout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(jLabel9)
                .addContainerGap(270, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        STU_LIST_PLayout.setVerticalGroup(
            STU_LIST_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STU_LIST_PLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(STU_LIST_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        STU_MANAGEMENT_P.add(STU_LIST_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 664, 426));

        STU_TOKEN_P.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel15.setText("토큰 관리");

        javax.swing.GroupLayout STU_TOKEN_PLayout = new javax.swing.GroupLayout(STU_TOKEN_P);
        STU_TOKEN_P.setLayout(STU_TOKEN_PLayout);
        STU_TOKEN_PLayout.setHorizontalGroup(
            STU_TOKEN_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, STU_TOKEN_PLayout.createSequentialGroup()
                .addContainerGap(281, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(274, 274, 274))
        );
        STU_TOKEN_PLayout.setVerticalGroup(
            STU_TOKEN_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STU_TOKEN_PLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(385, Short.MAX_VALUE))
        );

        STU_MANAGEMENT_P.add(STU_TOKEN_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 664, 426));

        MAIN_P.add(STU_MANAGEMENT_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, -1, -1));

        M_NOTICE_P.setBackground(new java.awt.Color(255, 255, 255));
        M_NOTICE_P.setVerifyInputWhenFocusTarget(false);
        M_NOTICE_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NOTICE_M_P.setPreferredSize(new java.awt.Dimension(100, 426));

        jLabel6.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel6.setText("MENU");

        NOTICE_L.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        NOTICE_L.setText("공지사항");
        NOTICE_L.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NOTICE_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NOTICE_LMouseClicked(evt);
            }
        });

        Declaration_L.setText("신고 및 문의");
        Declaration_L.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Declaration_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Declaration_LMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NOTICE_M_PLayout = new javax.swing.GroupLayout(NOTICE_M_P);
        NOTICE_M_P.setLayout(NOTICE_M_PLayout);
        NOTICE_M_PLayout.setHorizontalGroup(
            NOTICE_M_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NOTICE_M_PLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(NOTICE_M_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(NOTICE_L)
                    .addComponent(Declaration_L))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(NOTICE_M_PLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        NOTICE_M_PLayout.setVerticalGroup(
            NOTICE_M_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NOTICE_M_PLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NOTICE_L)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Declaration_L)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        M_NOTICE_P.add(NOTICE_M_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 426));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setPreferredSize(new java.awt.Dimension(454, 0));

        NOTICE_LIST.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "날짜", "제목", "작성자", "비고"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        NOTICE_LIST.setGridColor(new java.awt.Color(255, 255, 255));
        NOTICE_LIST.setPreferredSize(new java.awt.Dimension(660, 0));
        NOTICE_LIST.setSelectionBackground(new java.awt.Color(255, 255, 255));
        NOTICE_LIST.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        NOTICE_LIST.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        NOTICE_LIST.setShowGrid(true);
        jScrollPane1.setViewportView(NOTICE_LIST);

        M_NOTICE_P.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 56, 666, 370));

        NOTICE_TITLE.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        NOTICE_TITLE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NOTICE_TITLE.setText("공지사항");
        M_NOTICE_P.add(NOTICE_TITLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 160, -1));

        WRITE.setText("글쓰기");
        WRITE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        WRITE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WRITEMouseClicked(evt);
            }
        });
        M_NOTICE_P.add(WRITE, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, -1));

        CHANGE.setText("수정");
        CHANGE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CHANGE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CHANGEMouseClicked(evt);
            }
        });
        M_NOTICE_P.add(CHANGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));

        DELETE.setText("삭제");
        DELETE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DELETE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETEMouseClicked(evt);
            }
        });
        M_NOTICE_P.add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, -1, -1));

        MAIN_P.add(M_NOTICE_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 814, 426));

        RESERVATION_LIST_P.setBackground(new java.awt.Color(255, 255, 255));
        RESERVATION_LIST_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RESERVATION_M_P.setPreferredSize(new java.awt.Dimension(100, 426));

        jLabel10.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel10.setText("MENU");

        REQUEST_RESER.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        REQUEST_RESER.setText("예약 승인");
        REQUEST_RESER.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        REQUEST_RESER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REQUEST_RESERMouseClicked(evt);
            }
        });

        USING_HISTORY.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        USING_HISTORY.setText("사용 기록 조회");
        USING_HISTORY.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        USING_HISTORY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                USING_HISTORYMouseClicked(evt);
            }
        });

        USING_NOW.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        USING_NOW.setText("사용 현황 조회");
        USING_NOW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        USING_NOW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                USING_NOWMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout RESERVATION_M_PLayout = new javax.swing.GroupLayout(RESERVATION_M_P);
        RESERVATION_M_P.setLayout(RESERVATION_M_PLayout);
        RESERVATION_M_PLayout.setHorizontalGroup(
            RESERVATION_M_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RESERVATION_M_PLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(RESERVATION_M_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(USING_HISTORY)
                    .addComponent(jLabel10)
                    .addComponent(REQUEST_RESER)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(USING_NOW))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        RESERVATION_M_PLayout.setVerticalGroup(
            RESERVATION_M_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RESERVATION_M_PLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(REQUEST_RESER)
                .addGap(18, 18, 18)
                .addComponent(USING_HISTORY)
                .addGap(18, 18, 18)
                .addComponent(USING_NOW)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        RESERVATION_LIST_P.add(RESERVATION_M_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 426));

        USING_NOW_P.setBackground(new java.awt.Color(255, 255, 255));
        USING_NOW_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel19.setText("사용 현황 조회");
        USING_NOW_P.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 22, -1, -1));

        USING_915.setBackground(new java.awt.Color(255, 255, 255));
        USING_NOW_LAB.add(USING_915);
        USING_915.setSelected(true);
        USING_915.setText("915호");
        USING_915.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        USING_NOW_P.add(USING_915, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        USING_916.setBackground(new java.awt.Color(255, 255, 255));
        USING_NOW_LAB.add(USING_916);
        USING_916.setText("916호");
        USING_916.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        USING_NOW_P.add(USING_916, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        USING_918.setBackground(new java.awt.Color(255, 255, 255));
        USING_NOW_LAB.add(USING_918);
        USING_918.setText("918호");
        USING_918.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        USING_NOW_P.add(USING_918, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        USING_911.setBackground(new java.awt.Color(255, 255, 255));
        USING_NOW_LAB.add(USING_911);
        USING_911.setText("911호");
        USING_911.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        USING_NOW_P.add(USING_911, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        NOW_USING_PANEL1.setBackground(new java.awt.Color(255, 255, 255));
        NOW_USING_PANEL1.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        NOW_USING_PANEL1.setLayout(new java.awt.GridLayout(5, 8, 15, 15));
        USING_NOW_P.add(NOW_USING_PANEL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        NOW_USING_PANEL2.setBackground(new java.awt.Color(255, 255, 255));
        NOW_USING_PANEL2.setLayout(new java.awt.GridLayout(5, 4, 15, 15));
        USING_NOW_P.add(NOW_USING_PANEL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        RESERVATION_LIST_P.add(USING_NOW_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 664, 426));

        REQUEST_RESER_P.setBackground(new java.awt.Color(255, 255, 255));

        REQUEST_TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "일시", "강의실", "좌석", "학생명", "조별 활동", "승인 여부"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        REQUEST_TABLE.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane3.setViewportView(REQUEST_TABLE);

        jLabel8.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel8.setText("예약 승인");

        APPROVAL_ALL_BTN.setText("전체 승인");

        APPROVAL_BTN.setText("승인하기");

        javax.swing.GroupLayout REQUEST_RESER_PLayout = new javax.swing.GroupLayout(REQUEST_RESER_P);
        REQUEST_RESER_P.setLayout(REQUEST_RESER_PLayout);
        REQUEST_RESER_PLayout.setHorizontalGroup(
            REQUEST_RESER_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REQUEST_RESER_PLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel8)
                .addContainerGap(287, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, REQUEST_RESER_PLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(APPROVAL_BTN)
                .addGap(18, 18, 18)
                .addComponent(APPROVAL_ALL_BTN)
                .addGap(25, 25, 25))
        );
        REQUEST_RESER_PLayout.setVerticalGroup(
            REQUEST_RESER_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REQUEST_RESER_PLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(REQUEST_RESER_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(APPROVAL_ALL_BTN)
                    .addComponent(APPROVAL_BTN))
                .addGap(24, 24, 24))
        );

        RESERVATION_LIST_P.add(REQUEST_RESER_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 664, 426));

        USING_HISTORY_P.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel11.setText("사용 기록 조회");

        HISTORY_TALBE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "일시", "강의실", "좌석", "학생 명", "조별 활동", "승인 여부"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        HISTORY_TALBE.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        HISTORY_TALBE.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(HISTORY_TALBE);

        javax.swing.GroupLayout USING_HISTORY_PLayout = new javax.swing.GroupLayout(USING_HISTORY_P);
        USING_HISTORY_P.setLayout(USING_HISTORY_PLayout);
        USING_HISTORY_PLayout.setHorizontalGroup(
            USING_HISTORY_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(USING_HISTORY_PLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );
        USING_HISTORY_PLayout.setVerticalGroup(
            USING_HISTORY_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(USING_HISTORY_PLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        RESERVATION_LIST_P.add(USING_HISTORY_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 664, 426));

        MAIN_P.add(RESERVATION_LIST_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 814, 426));

        INPUT_TIME_P.setBackground(new java.awt.Color(255, 255, 255));
        INPUT_TIME_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        INPUT_M_P.setPreferredSize(new java.awt.Dimension(100, 426));
        INPUT_M_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel12.setText("MENU");
        INPUT_M_P.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));
        INPUT_M_P.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 106, 10));

        INPUT_CLASS.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        INPUT_CLASS.setText("강의 시간표 입력");
        INPUT_CLASS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        INPUT_CLASS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INPUT_CLASSMouseClicked(evt);
            }
        });
        INPUT_M_P.add(INPUT_CLASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        INPUT_SPECIAL.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        INPUT_SPECIAL.setText("특강 시간표 입력");
        INPUT_SPECIAL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        INPUT_SPECIAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INPUT_SPECIALMouseClicked(evt);
            }
        });
        INPUT_M_P.add(INPUT_SPECIAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        INPUT_TIME_P.add(INPUT_M_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 426));

        INPUT_CLASS_TIME_P.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel13.setText("강의 시간표 입력");

        CLASS_LAB_915.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(CLASS_LAB_915);
        CLASS_LAB_915.setText("915호");

        CLASS_LAB_916.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(CLASS_LAB_916);
        CLASS_LAB_916.setText("916호");

        CLASS_LAB_918.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(CLASS_LAB_918);
        CLASS_LAB_918.setText("918호");

        CLASS_LAB_911.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(CLASS_LAB_911);
        CLASS_LAB_911.setText("911호");

        jLabel22.setText("시작 시간");

        CLASS_START_TIME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 : 00", "2 : 00", "3 : 00", "4 : 00", "5 : 00", "6 : 00", "7 : 00", "8 : 00", "9 : 00", "10 : 00", "11 : 00", "12 : 00", "13 : 00", "14 : 00", "15 : 00", "16 : 00", "17 : 00", "18 : 00", "19 : 00", "20 : 00", "21 : 00", "22 : 00", "23 : 00", "24 : 00" }));

        jLabel23.setText("종료시간");

        CLASS_END_TIME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 : 00", "2 : 00", "3 : 00", "4 : 00", "5 : 00", "6 : 00", "7 : 00", "8 : 00", "9 : 00", "10 : 00", "11 : 00", "12 : 00", "13 : 00", "14 : 00", "15 : 00", "16 : 00", "17 : 00", "18 : 00", "19 : 00", "20 : 00", "21 : 00", "22 : 00", "23 : 00", "24 : 00" }));

        jLabel25.setText("요일");

        jLabel26.setText("강의실");

        jLabel27.setText("시간");

        CLASS_date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "월", "화", "수", "목", "금", "토", "일" }));

        CLASS_SELECT_DAY_BTN.setBackground(new java.awt.Color(255, 255, 255));
        CLASS_SELECT_DAY_BTN.setText("등록");

        javax.swing.GroupLayout INPUT_CLASS_TIME_PLayout = new javax.swing.GroupLayout(INPUT_CLASS_TIME_P);
        INPUT_CLASS_TIME_P.setLayout(INPUT_CLASS_TIME_PLayout);
        INPUT_CLASS_TIME_PLayout.setHorizontalGroup(
            INPUT_CLASS_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(INPUT_CLASS_TIME_PLayout.createSequentialGroup()
                .addGroup(INPUT_CLASS_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(INPUT_CLASS_TIME_PLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel13))
                    .addGroup(INPUT_CLASS_TIME_PLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(INPUT_CLASS_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(INPUT_CLASS_TIME_PLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel26)
                                .addGap(148, 148, 148)
                                .addComponent(jLabel27)
                                .addGap(132, 132, 132)
                                .addComponent(jLabel25))
                            .addGroup(INPUT_CLASS_TIME_PLayout.createSequentialGroup()
                                .addGap(410, 410, 410)
                                .addComponent(CLASS_SELECT_DAY_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(INPUT_CLASS_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(INPUT_CLASS_TIME_PLayout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addGroup(INPUT_CLASS_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CLASS_LAB_915, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CLASS_LAB_916, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CLASS_LAB_918, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CLASS_LAB_911, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(107, 107, 107)
                                    .addGroup(INPUT_CLASS_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel22)
                                        .addComponent(CLASS_START_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(INPUT_CLASS_TIME_PLayout.createSequentialGroup()
                                            .addComponent(jLabel23)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(CLASS_date, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(CLASS_END_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        INPUT_CLASS_TIME_PLayout.setVerticalGroup(
            INPUT_CLASS_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(INPUT_CLASS_TIME_PLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(38, 38, 38)
                .addGroup(INPUT_CLASS_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel25))
                .addGap(12, 12, 12)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(INPUT_CLASS_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(INPUT_CLASS_TIME_PLayout.createSequentialGroup()
                        .addComponent(CLASS_LAB_915)
                        .addGap(3, 3, 3)
                        .addComponent(CLASS_LAB_916)
                        .addGap(3, 3, 3)
                        .addComponent(CLASS_LAB_918)
                        .addGap(3, 3, 3)
                        .addComponent(CLASS_LAB_911))
                    .addGroup(INPUT_CLASS_TIME_PLayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(CLASS_START_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(INPUT_CLASS_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(INPUT_CLASS_TIME_PLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(INPUT_CLASS_TIME_PLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(CLASS_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addComponent(CLASS_END_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(CLASS_SELECT_DAY_BTN)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        INPUT_TIME_P.add(INPUT_CLASS_TIME_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 664, 426));

        INPUT_SPECIAL_TIME_P.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel14.setText("특강 및 세미나 시간표 입력");

        SPECIAL_LAB_918.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(SPECIAL_LAB_918);
        SPECIAL_LAB_918.setText("918호");

        SPECIAL_SELECT_DAY_BTN.setBackground(new java.awt.Color(255, 255, 255));
        SPECIAL_SELECT_DAY_BTN.setText("선택");

        SPECIAL_LAB_911.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(SPECIAL_LAB_911);
        SPECIAL_LAB_911.setText("911호");

        jLabel24.setText("시작 시간");

        SPECIAL_START_TIME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 : 00", "2 : 00", "3 : 00", "4 : 00", "5 : 00", "6 : 00", "7 : 00", "8 : 00", "9 : 00", "10 : 00", "11 : 00", "12 : 00", "13 : 00", "14 : 00", "15 : 00", "16 : 00", "17 : 00", "18 : 00", "19 : 00", "20 : 00", "21 : 00", "22 : 00", "23 : 00", "24 : 00" }));

        jLabel28.setText("종료시간");

        SPECIAL_END_TIME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 : 00", "2 : 00", "3 : 00", "4 : 00", "5 : 00", "6 : 00", "7 : 00", "8 : 00", "9 : 00", "10 : 00", "11 : 00", "12 : 00", "13 : 00", "14 : 00", "15 : 00", "16 : 00", "17 : 00", "18 : 00", "19 : 00", "20 : 00", "21 : 00", "22 : 00", "23 : 00", "24 : 00" }));

        jLabel29.setText("요일");

        jLabel30.setText("강의실");

        jLabel31.setText("시간");

        SPECIAL_LAB_915.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(SPECIAL_LAB_915);
        SPECIAL_LAB_915.setSelected(true);
        SPECIAL_LAB_915.setText("915호");

        SPECIAL_LAB_916.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(SPECIAL_LAB_916);
        SPECIAL_LAB_916.setText("916호");

        jLabel16.setText("년");

        jLabel17.setText("월");

        jLabel18.setText("일");

        javax.swing.GroupLayout INPUT_SPECIAL_TIME_PLayout = new javax.swing.GroupLayout(INPUT_SPECIAL_TIME_P);
        INPUT_SPECIAL_TIME_P.setLayout(INPUT_SPECIAL_TIME_PLayout);
        INPUT_SPECIAL_TIME_PLayout.setHorizontalGroup(
            INPUT_SPECIAL_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(INPUT_SPECIAL_TIME_PLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(INPUT_SPECIAL_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, INPUT_SPECIAL_TIME_PLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, INPUT_SPECIAL_TIME_PLayout.createSequentialGroup()
                        .addGroup(INPUT_SPECIAL_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(INPUT_SPECIAL_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, INPUT_SPECIAL_TIME_PLayout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addGroup(INPUT_SPECIAL_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(SPECIAL_LAB_915, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SPECIAL_LAB_916, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SPECIAL_LAB_918, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SPECIAL_LAB_911))
                                    .addGap(107, 107, 107)
                                    .addGroup(INPUT_SPECIAL_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel28)
                                        .addComponent(SPECIAL_START_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel24)
                                        .addComponent(SPECIAL_END_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(INPUT_SPECIAL_TIME_PLayout.createSequentialGroup()
                                .addGap(380, 380, 380)
                                .addGroup(INPUT_SPECIAL_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(INPUT_SPECIAL_TIME_PLayout.createSequentialGroup()
                                        .addGroup(INPUT_SPECIAL_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SPECIAL_YEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SPECIAL_DATE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SPECIAL_MONTH, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(SPECIAL_SELECT_DAY_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(INPUT_SPECIAL_TIME_PLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel30)
                                .addGap(148, 148, 148)
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel29)
                                .addGap(53, 53, 53)))
                        .addGap(71, 71, 71))))
        );
        INPUT_SPECIAL_TIME_PLayout.setVerticalGroup(
            INPUT_SPECIAL_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(INPUT_SPECIAL_TIME_PLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel14)
                .addGap(45, 45, 45)
                .addGroup(INPUT_SPECIAL_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addGroup(INPUT_SPECIAL_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel31)
                        .addComponent(jLabel29)))
                .addGap(12, 12, 12)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(5, 5, 5)
                .addGroup(INPUT_SPECIAL_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(INPUT_SPECIAL_TIME_PLayout.createSequentialGroup()
                        .addComponent(SPECIAL_LAB_915)
                        .addGap(3, 3, 3)
                        .addComponent(SPECIAL_LAB_916)
                        .addGap(3, 3, 3)
                        .addComponent(SPECIAL_LAB_918)
                        .addGap(3, 3, 3)
                        .addComponent(SPECIAL_LAB_911))
                    .addGroup(INPUT_SPECIAL_TIME_PLayout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(SPECIAL_START_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(SPECIAL_END_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(INPUT_SPECIAL_TIME_PLayout.createSequentialGroup()
                        .addComponent(SPECIAL_MONTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(INPUT_SPECIAL_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(INPUT_SPECIAL_TIME_PLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(SPECIAL_YEAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(INPUT_SPECIAL_TIME_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(INPUT_SPECIAL_TIME_PLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(SPECIAL_DATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(14, 14, 14)
                .addComponent(SPECIAL_SELECT_DAY_BTN)
                .addContainerGap())
        );

        INPUT_TIME_P.add(INPUT_SPECIAL_TIME_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 664, 426));

        MAIN_P.add(INPUT_TIME_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 814, 426));

        UNDER_P.add(MAIN_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, 460));

        TITLE_P.setBackground(new java.awt.Color(0, 204, 255));
        TITLE_P.setMinimumSize(new java.awt.Dimension(810, 122));
        TITLE_P.setPreferredSize(new java.awt.Dimension(814, 128));
        TITLE_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TITLE.setFont(new java.awt.Font("맑은 고딕", 1, 48)); // NOI18N
        TITLE.setForeground(new java.awt.Color(255, 255, 255));
        TITLE.setText("S.M.P");
        TITLE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TITLE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TITLEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TITLEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TITLEMouseExited(evt);
            }
        });
        TITLE_P.add(TITLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 30, -1, -1));

        LOGOUT.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        LOGOUT.setForeground(new java.awt.Color(255, 255, 255));
        LOGOUT.setText("로그아웃");
        LOGOUT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LOGOUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGOUTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LOGOUTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LOGOUTMouseExited(evt);
            }
        });
        TITLE_P.add(LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 102, -1, -1));

        jLabel3.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("님");
        TITLE_P.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 102, -1, -1));

        SNAME.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        SNAME.setForeground(new java.awt.Color(255, 255, 255));
        SNAME.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SNAME.setText("조교");
        TITLE_P.add(SNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, -1, 40));

        UNDER_P.add(TITLE_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 814, 130));

        getContentPane().add(UNDER_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TITLEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TITLEMouseClicked
        //타이틀 클릭시 메인 패널로 이동
        panelClear();
        M_NOTICE_P.setVisible(true);
    }//GEN-LAST:event_TITLEMouseClicked

    private void LOGOUTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTMouseClicked
        //로그아웃 버튼 클릭시 로그인 화면으로 이동
        Login l = new Login();
        l.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_LOGOUTMouseClicked

    private void M_MENU4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU4MouseEntered
        // 메뉴 4번 마우스 호버시
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.GRAY);
        jLabel5.setForeground(Color.white);
    }//GEN-LAST:event_M_MENU4MouseEntered

    private void M_MENU4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU4MouseExited
        // 메뉴 4번 마우스 밖으로
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.white);
        jLabel5.setForeground(Color.black);
    }//GEN-LAST:event_M_MENU4MouseExited

    private void M_MENU3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU3MouseEntered
        // 메뉴 3번 마우스 호버시
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.GRAY);
        jLabel4.setForeground(Color.white);
    }//GEN-LAST:event_M_MENU3MouseEntered

    private void M_MENU3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU3MouseExited
        // 메뉴 3번 마우스 밖으로
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.white);
        jLabel4.setForeground(Color.black);
    }//GEN-LAST:event_M_MENU3MouseExited

    private void M_MENU2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU2MouseEntered
        // 메뉴 2번 마우스 호버시
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.GRAY);
        jLabel1.setForeground(Color.white);
    }//GEN-LAST:event_M_MENU2MouseEntered

    private void M_MENU2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU2MouseExited
        // 메뉴 2번 마우스 밖으로
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.white);
        jLabel1.setForeground(Color.black);
    }//GEN-LAST:event_M_MENU2MouseExited

    private void M_MENU1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU1MouseEntered
        // 메뉴 1번 마우스 호버시
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.GRAY);
        jLabel2.setForeground(Color.white);
    }//GEN-LAST:event_M_MENU1MouseEntered

    private void M_MENU1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU1MouseExited
        // 메뉴 1번 마우스 밖으로
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.white);
        jLabel2.setForeground(Color.black);
    }//GEN-LAST:event_M_MENU1MouseExited

    private void LOGOUTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTMouseEntered
        // 로그아웃 호버 시 색 변경
        LOGOUT.setForeground(Color.black);
    }//GEN-LAST:event_LOGOUTMouseEntered

    private void LOGOUTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTMouseExited
        // 로그아웃 마우스 바깥으로
        LOGOUT.setForeground(Color.white);
    }//GEN-LAST:event_LOGOUTMouseExited

    private void TITLEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TITLEMouseEntered
        // 타이틀 호버시 색 변경
        TITLE.setForeground(Color.black);
    }//GEN-LAST:event_TITLEMouseEntered

    private void TITLEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TITLEMouseExited
        // 타이틀 마우스 바깥으로
        TITLE.setForeground(Color.white);
    }//GEN-LAST:event_TITLEMouseExited

    private void M_MENU4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU4MouseClicked
        // 게시판 메뉴 선택시
        // 컨트롤러에 있는 공지사항 목록 출력 함수 사용
        panelClear();
        M_NOTICE_P.setVisible(true);
        NOTICE_TITLE.setText("공지사항");
    }//GEN-LAST:event_M_MENU4MouseClicked

    private void M_MENU3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU3MouseClicked
        //실습실 시간표 입력 메뉴 선택 시
        panelClear();
        INPUT_TIME_P.setVisible(true);
        INPUT_CLASS.setVisible(true);
    }//GEN-LAST:event_M_MENU3MouseClicked

    private void M_MENU2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU2MouseClicked
        // 예약 내역 조회 패널로 이동
        panelClear();
        USING_NOW_P.setVisible(false);
        RESERVATION_LIST_P.setVisible(true);
        USING_HISTORY_P.setVisible(false);
        REQUEST_RESER_P.setVisible(true);
        // 컨트롤러에 있는 예약 조회 함수로 테이블 값 채우기
    }//GEN-LAST:event_M_MENU2MouseClicked

    private void M_MENU1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU1MouseClicked
        // 학생 명단 관리 패널로 이동
        panelClear();
        STU_MANAGEMENT_P.setVisible(true);
        STU_LIST_P.setVisible(true);
        // 컨트롤러에서 예약 신청 테이블 띄워주기
    }//GEN-LAST:event_M_MENU1MouseClicked

    private void DELETEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEMouseClicked
        //리스트에 있는 게시글 삭제(본인 글에 한해서)
        // 컨트롤러에 있는 목록 삭제 함수 사용
    }//GEN-LAST:event_DELETEMouseClicked

    private void CHANGEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CHANGEMouseClicked
        // 글 수정 화면 띄우기(본인 글에 한해서)
        Write_Post w = new Write_Post();
        w.setVisible(true);
    }//GEN-LAST:event_CHANGEMouseClicked

    private void WRITEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WRITEMouseClicked
        // 글 작성 화면 띄우기
        Write_Post w = new Write_Post();
        w.setVisible(true);
    }//GEN-LAST:event_WRITEMouseClicked

    private void Declaration_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Declaration_LMouseClicked
        // 메뉴에 신고 및 문의 클릭시 신고 및 문의 내용 출력
        // 컨트롤러에 있는 신고 및 문의사항 출력 함수 사용
        NOTICE_TITLE.setText("신고 및 문의");
    }//GEN-LAST:event_Declaration_LMouseClicked

    private void NOTICE_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NOTICE_LMouseClicked
        // 메뉴에 공지사항 클릭시 공지사항 내용 출력
        // 컨트롤러에 있는 공지사항 출력 함수 사용
        NOTICE_TITLE.setText("공지사항");
    }//GEN-LAST:event_NOTICE_LMouseClicked

    private void REQUEST_RESERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REQUEST_RESERMouseClicked
        // 예약내역 관리 메뉴 밑 예약 승인 메뉴 클릭시
        USING_HISTORY_P.setVisible(false);
        REQUEST_RESER_P.setVisible(true);
        USING_NOW_P.setVisible(false);
        // 컨트롤러에서 예약 신청 테이블 띄워주기
    }//GEN-LAST:event_REQUEST_RESERMouseClicked

    private void USING_HISTORYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_USING_HISTORYMouseClicked
        // 예약내역 관리 메뉴 밑 예약 승인 메뉴 클릭시
        USING_HISTORY_P.setVisible(true);
        REQUEST_RESER_P.setVisible(false);
        USING_NOW_P.setVisible(false);
        // 컨트롤러에서 예약 신청 테이블 띄워주기
    }//GEN-LAST:event_USING_HISTORYMouseClicked

    private void STU_LISTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STU_LISTMouseClicked
        // 학생 명단 관리 메뉴 밑 학생 명단 관리 메뉴 클릭시
        //토큰관리 패널 false
        STU_LIST_P.setVisible(true);
        // 컨트롤러에서 예약 신청 테이블 띄워주기
    }//GEN-LAST:event_STU_LISTMouseClicked

    private void INPUT_CLASSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INPUT_CLASSMouseClicked
        // 실습실 시간표 입력 밑 강의 시간표 입력
        INPUT_CLASS_TIME_P.setVisible(true);
        INPUT_SPECIAL_TIME_P.setVisible(false);
    }//GEN-LAST:event_INPUT_CLASSMouseClicked

    private void INPUT_SPECIALMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INPUT_SPECIALMouseClicked
        // 실습실 시간표 입력 밑 특강 시간표 입력
        INPUT_CLASS_TIME_P.setVisible(false);
        INPUT_SPECIAL_TIME_P.setVisible(true);
    }//GEN-LAST:event_INPUT_SPECIALMouseClicked

    private void STU_TOKENMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STU_TOKENMouseClicked
        // 학생 명단 관리 밑 토큰 관리
        STU_LIST_P.setVisible(false);
        STU_TOKEN_P.setVisible(true);
    }//GEN-LAST:event_STU_TOKENMouseClicked

    private void USING_NOWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_USING_NOWMouseClicked
        // 현재 사용자 조회
        USING_HISTORY_P.setVisible(false);
        REQUEST_RESER_P.setVisible(false);
        USING_NOW_P.setVisible(true);
        int co =0;
        int j=0;
        JLabel [] seat = new JLabel[40];
        
        for(int i=0; i<40; i++){
            System.out.println("co%4 = " + co%4);
            System.out.println(" co = "+co);
            System.out.println("j = " + j);
            seat[i] = new JLabel("<html><body style='text-align:center;'> "+Integer.toString(i+1)+"<br>"+20183150+"</html>",JLabel.CENTER);
            if(j == 0){
                NOW_USING_PANEL1.add(seat[i]);
                System.out.println("패널 1에 추가\n");
            }else if(j == 1){
                NOW_USING_PANEL2.add(seat[i]);
                System.out.println("패널 2에 추가\n");
            }
            if( co%4 == 3 ){
                if(j==0){
                    j = 1;
                }else if (j == 1){
                    j=0;
                }
            }
            
            co++; 
        }
    }//GEN-LAST:event_USING_NOWMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton APPROVAL_ALL_BTN;
    private javax.swing.JButton APPROVAL_BTN;
    private javax.swing.JLabel CHANGE;
    private javax.swing.JComboBox<String> CLASS_END_TIME;
    private javax.swing.JRadioButton CLASS_LAB_911;
    private javax.swing.JRadioButton CLASS_LAB_915;
    private javax.swing.JRadioButton CLASS_LAB_916;
    private javax.swing.JRadioButton CLASS_LAB_918;
    private javax.swing.JButton CLASS_SELECT_DAY_BTN;
    private javax.swing.JComboBox<String> CLASS_START_TIME;
    private javax.swing.JComboBox<String> CLASS_date;
    private javax.swing.JLabel DELETE;
    private javax.swing.JLabel Declaration_L;
    private javax.swing.JTable HISTORY_TALBE;
    private javax.swing.JLabel INPUT_CLASS;
    private javax.swing.JPanel INPUT_CLASS_TIME_P;
    private javax.swing.JPanel INPUT_M_P;
    private javax.swing.JLabel INPUT_SPECIAL;
    private javax.swing.JPanel INPUT_SPECIAL_TIME_P;
    private javax.swing.JPanel INPUT_TIME_P;
    private javax.swing.JLabel LOGOUT;
    private javax.swing.JPanel MAIN_P;
    private javax.swing.JPanel M_MENU1;
    private javax.swing.JPanel M_MENU2;
    private javax.swing.JPanel M_MENU3;
    private javax.swing.JPanel M_MENU4;
    private javax.swing.JPanel M_MENU_P;
    private javax.swing.JPanel M_NOTICE_P;
    private javax.swing.JLabel NOTICE_L;
    private javax.swing.JTable NOTICE_LIST;
    private javax.swing.JPanel NOTICE_M_P;
    private javax.swing.JLabel NOTICE_TITLE;
    private javax.swing.JPanel NOW_USING_PANEL1;
    private javax.swing.JPanel NOW_USING_PANEL2;
    private javax.swing.JLabel REQUEST_RESER;
    private javax.swing.JPanel REQUEST_RESER_P;
    private javax.swing.JTable REQUEST_TABLE;
    private javax.swing.JPanel RESERVATION_LIST_P;
    private javax.swing.JPanel RESERVATION_M_P;
    private javax.swing.JLabel SNAME;
    private javax.swing.JComboBox<String> SPECIAL_DATE;
    private javax.swing.JComboBox<String> SPECIAL_END_TIME;
    private javax.swing.JRadioButton SPECIAL_LAB_911;
    private javax.swing.JRadioButton SPECIAL_LAB_915;
    private javax.swing.JRadioButton SPECIAL_LAB_916;
    private javax.swing.JRadioButton SPECIAL_LAB_918;
    private javax.swing.JComboBox<String> SPECIAL_MONTH;
    private javax.swing.JButton SPECIAL_SELECT_DAY_BTN;
    private javax.swing.JComboBox<String> SPECIAL_START_TIME;
    private javax.swing.JComboBox<String> SPECIAL_YEAR;
    private javax.swing.JLabel STU_LIST;
    private javax.swing.JPanel STU_LIST_P;
    private javax.swing.JTable STU_LIST_T;
    private javax.swing.JPanel STU_MANAGEMENT_P;
    private javax.swing.JPanel STU_M_P;
    private javax.swing.JLabel STU_TOKEN;
    private javax.swing.JPanel STU_TOKEN_P;
    private javax.swing.JLabel TITLE;
    private javax.swing.JPanel TITLE_P;
    private javax.swing.JPanel UNDER_P;
    private javax.swing.JRadioButton USING_911;
    private javax.swing.JRadioButton USING_915;
    private javax.swing.JRadioButton USING_916;
    private javax.swing.JRadioButton USING_918;
    private javax.swing.JLabel USING_HISTORY;
    private javax.swing.JPanel USING_HISTORY_P;
    private javax.swing.JLabel USING_NOW;
    private javax.swing.ButtonGroup USING_NOW_LAB;
    private javax.swing.JPanel USING_NOW_P;
    private javax.swing.JLabel WRITE;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
