/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

//import Controller.Timetable_controller;
import Controller.UseLab_controller;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.Calendar;
import javax.swing.*;


/**
 *
 * @author 20183150 김부성
 * 클래스 사용 용도 : 관리자 화면 제작 클래스
 * 
 */
public class Manager_Main extends javax.swing.JFrame {

    public Manager_Main() {
        initComponents();
        panelClear();
        M_NOTICE_P.setVisible(true); //초기 메인 화면 출력
    }
    
    public void panelClear(){ // 모든 패널을 지우는 함수
        M_NOTICE_P.setVisible(false);
        STU_MANAGEMENT_P.setVisible(false);
        INPUT_TIME_P.setVisible(false);
        RESERVATION_LIST_P.setVisible(false);
    }
    public void setaddActionListener(ActionListener listener) {
       APPROVAL_ALL_BTN.addActionListener(listener); // 일괄 승인 버튼 리스너
       APPROVAL_BTN.addActionListener(listener); // 승인하기 버튼 리스너
       SPECIAL_SELECT_DAY_BTN.addActionListener(listener);//특강 시간표 입력
       CLASS_SELECT_DAY_BTN.addActionListener(listener);//강의 시간표 입력
       INPUT_TOKEN.addActionListener(listener); // 새 토큰 생성
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        INPUT_CLASS_LAB = new javax.swing.ButtonGroup();
        INPUT_SPECIAL_LAB = new javax.swing.ButtonGroup();
        USING_NOW_LAB = new javax.swing.ButtonGroup();
        SEMESTER_GROUP = new javax.swing.ButtonGroup();
        UNDER_P = new javax.swing.JPanel();
        MAIN_P = new javax.swing.JPanel();
        M_MENU_P = new javax.swing.JPanel();
        M_MENU2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        M_MENU3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        M_MENU4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        M_MENU1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        INPUT_TIME_P = new javax.swing.JPanel();
        INPUT_M_P = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        INPUT_CLASS = new javax.swing.JLabel();
        INPUT_SPECIAL = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        INPUT_CLASS_TIME_P = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        CLASS_LAB_915 = new javax.swing.JRadioButton();
        CLASS_LAB_916 = new javax.swing.JRadioButton();
        CLASS_LAB_918 = new javax.swing.JRadioButton();
        CLASS_LAB_911 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        INPUT_CLASS_STIME = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        INPUT_CLASS_ETIME = new javax.swing.JComboBox<>();
        INPUT_CLASS_DAY = new javax.swing.JComboBox<>();
        CLASS_SELECT_DAY_BTN = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        SEMESTER1 = new javax.swing.JRadioButton();
        SEMESTER2 = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        INPUT_CLASS_YEAR = new javax.swing.JComboBox<>();
        INPUT_CLASS_PRO = new javax.swing.JTextField();
        INPUT_CLASS_NUM = new javax.swing.JTextField();
        INPUT_CLASS_NAME = new javax.swing.JTextField();
        INPUT_CLASS_DIVISON = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        INPUT_SPECIAL_TIME_P = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        INPUT_SEMINAR_MONTH = new javax.swing.JComboBox<>();
        SPECIAL_LAB_918 = new javax.swing.JRadioButton();
        SPECIAL_SELECT_DAY_BTN = new javax.swing.JButton();
        SPECIAL_LAB_911 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        INPUT_SEMINAR_STIME = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        INPUT_SEMINAR_ETIME = new javax.swing.JComboBox<>();
        SPECIAL_LAB_915 = new javax.swing.JRadioButton();
        SPECIAL_LAB_916 = new javax.swing.JRadioButton();
        INPUT_SEMINAR_YEAR = new javax.swing.JComboBox<>();
        INPUT_SEMINAR_DATE = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        INPUT_SEMINAR_ID = new javax.swing.JTextField();
        INPUT_SEMINAR_NAME = new javax.swing.JTextField();
        RESERVATION_LIST_P = new javax.swing.JPanel();
        RESERVATION_M_P = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        REQUEST_RESER = new javax.swing.JLabel();
        USING_HISTORY = new javax.swing.JLabel();
        USING_NOW = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        USING_NOW_P = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        USING_915 = new javax.swing.JRadioButton();
        USING_916 = new javax.swing.JRadioButton();
        USING_918 = new javax.swing.JRadioButton();
        USING_911 = new javax.swing.JRadioButton();
        NOW_USING_PANEL1 = new javax.swing.JPanel();
        NOW_USING_PANEL2 = new javax.swing.JPanel();
        REQUEST_RESER_P = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        REQUEST_TABLE = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        APPROVAL_ALL_BTN = new javax.swing.JButton();
        APPROVAL_BTN = new javax.swing.JButton();
        USING_HISTORY_P = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        HISTORY_TALBE = new javax.swing.JTable();
        STU_MANAGEMENT_P = new javax.swing.JPanel();
        STU_M_P = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        STU_LIST = new javax.swing.JLabel();
        STU_TOKEN = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        STU_LIST_P = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        STU_LIST_T = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        STU_TOKEN_P = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        TOKEN = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        INPUT_TOKEN = new javax.swing.JButton();
        M_NOTICE_P = new javax.swing.JPanel();
        NOTICE_M_P = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        NOTICE_L = new javax.swing.JLabel();
        Declaration_L = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        NOTICE_LIST = new javax.swing.JTable();
        NOTICE_TITLE = new javax.swing.JLabel();
        WRITE = new javax.swing.JLabel();
        CHANGE = new javax.swing.JLabel();
        DELETE = new javax.swing.JLabel();
        TITLE_P = new javax.swing.JPanel();
        TITLE = new javax.swing.JLabel();
        LOGOUT = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SNAME = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("실습실 관리 시스템");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UNDER_P.setMinimumSize(new java.awt.Dimension(814, 590));
        UNDER_P.setPreferredSize(new java.awt.Dimension(815, 600));
        UNDER_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MAIN_P.setBackground(new java.awt.Color(255, 255, 255));
        MAIN_P.setPreferredSize(new java.awt.Dimension(815, 470));
        MAIN_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        M_MENU_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        M_MENU2.setBackground(new java.awt.Color(255, 255, 255));
        M_MENU2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        M_MENU2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        M_MENU2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        M_MENU2.setPreferredSize(new java.awt.Dimension(204, 3));
        M_MENU2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_MENU2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                M_MENU2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                M_MENU2MouseExited(evt);
            }
        });
        M_MENU2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("예약 내역 조회");
        M_MENU2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 34));

        M_MENU_P.add(M_MENU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 0, 205, 34));

        M_MENU3.setBackground(new java.awt.Color(255, 255, 255));
        M_MENU3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        M_MENU3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        M_MENU3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_MENU3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                M_MENU3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                M_MENU3MouseExited(evt);
            }
        });
        M_MENU3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("실습실 시간표 입력 ");
        M_MENU3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 34));

        M_MENU_P.add(M_MENU3, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 0, 205, 34));

        M_MENU4.setBackground(new java.awt.Color(255, 255, 255));
        M_MENU4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        M_MENU4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        M_MENU4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_MENU4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                M_MENU4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                M_MENU4MouseExited(evt);
            }
        });
        M_MENU4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("게시판");
        M_MENU4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 34));

        M_MENU_P.add(M_MENU4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 205, 34));

        M_MENU1.setBackground(new java.awt.Color(255, 255, 255));
        M_MENU1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        M_MENU1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        M_MENU1.setPreferredSize(new java.awt.Dimension(204, 34));
        M_MENU1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_MENU1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                M_MENU1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                M_MENU1MouseExited(evt);
            }
        });
        M_MENU1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText(" 학생 명단 관리");
        M_MENU1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 34));

        M_MENU_P.add(M_MENU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 205, 34));

        MAIN_P.add(M_MENU_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 34));

        INPUT_TIME_P.setBackground(new java.awt.Color(255, 255, 255));
        INPUT_TIME_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        INPUT_M_P.setBackground(new java.awt.Color(255, 255, 255));
        INPUT_M_P.setPreferredSize(new java.awt.Dimension(100, 426));
        INPUT_M_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel12.setText("MENU");
        INPUT_M_P.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 41, -1, -1));
        INPUT_M_P.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, 110, 10));

        INPUT_CLASS.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        INPUT_CLASS.setText("강의 시간표 입력");
        INPUT_CLASS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        INPUT_CLASS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INPUT_CLASSMouseClicked(evt);
            }
        });
        INPUT_M_P.add(INPUT_CLASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 90, -1, -1));

        INPUT_SPECIAL.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        INPUT_SPECIAL.setText("특강 시간표 입력");
        INPUT_SPECIAL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        INPUT_SPECIAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INPUT_SPECIALMouseClicked(evt);
            }
        });
        INPUT_M_P.add(INPUT_SPECIAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 120, -1, -1));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        INPUT_M_P.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 10, 2, 420));

        INPUT_TIME_P.add(INPUT_M_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 440));

        INPUT_CLASS_TIME_P.setBackground(new java.awt.Color(255, 255, 255));
        INPUT_CLASS_TIME_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel13.setText("강의 시간표 입력");
        INPUT_CLASS_TIME_P.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 10, -1, -1));

        CLASS_LAB_915.setBackground(new java.awt.Color(255, 255, 255));
        INPUT_CLASS_LAB.add(CLASS_LAB_915);
        CLASS_LAB_915.setSelected(true);
        CLASS_LAB_915.setText("915호");
        INPUT_CLASS_TIME_P.add(CLASS_LAB_915, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        CLASS_LAB_916.setBackground(new java.awt.Color(255, 255, 255));
        INPUT_CLASS_LAB.add(CLASS_LAB_916);
        CLASS_LAB_916.setText("916호");
        INPUT_CLASS_TIME_P.add(CLASS_LAB_916, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        CLASS_LAB_918.setBackground(new java.awt.Color(255, 255, 255));
        INPUT_CLASS_LAB.add(CLASS_LAB_918);
        CLASS_LAB_918.setText("918호");
        INPUT_CLASS_TIME_P.add(CLASS_LAB_918, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        CLASS_LAB_911.setBackground(new java.awt.Color(255, 255, 255));
        INPUT_CLASS_LAB.add(CLASS_LAB_911);
        CLASS_LAB_911.setText("911호");
        INPUT_CLASS_TIME_P.add(CLASS_LAB_911, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        jLabel22.setText("시작 시간");
        INPUT_CLASS_TIME_P.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, 20));

        INPUT_CLASS_STIME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", " " }));
        INPUT_CLASS_TIME_P.add(INPUT_CLASS_STIME, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 100, 20));

        jLabel23.setText("종료시간");
        INPUT_CLASS_TIME_P.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, 20));

        INPUT_CLASS_ETIME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00" }));
        INPUT_CLASS_TIME_P.add(INPUT_CLASS_ETIME, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 100, 20));

        INPUT_CLASS_DAY.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "월", "화", "수", "목", "금", "토", "일" }));
        INPUT_CLASS_TIME_P.add(INPUT_CLASS_DAY, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 100, -1));

        CLASS_SELECT_DAY_BTN.setBackground(new java.awt.Color(255, 255, 255));
        CLASS_SELECT_DAY_BTN.setText("등록");
        CLASS_SELECT_DAY_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLASS_SELECT_DAY_BTNActionPerformed(evt);
            }
        });
        INPUT_CLASS_TIME_P.add(CLASS_SELECT_DAY_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 70, -1));

        jLabel21.setText("요일");
        INPUT_CLASS_TIME_P.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jLabel32.setText("강의 번호");
        INPUT_CLASS_TIME_P.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel33.setText("강의명");
        INPUT_CLASS_TIME_P.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jLabel34.setText("교수번호");
        INPUT_CLASS_TIME_P.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel35.setText("분반");
        INPUT_CLASS_TIME_P.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jLabel36.setText("학기");
        INPUT_CLASS_TIME_P.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        SEMESTER1.setBackground(new java.awt.Color(255, 255, 255));
        SEMESTER_GROUP.add(SEMESTER1);
        SEMESTER1.setSelected(true);
        SEMESTER1.setText("1");
        INPUT_CLASS_TIME_P.add(SEMESTER1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        SEMESTER2.setBackground(new java.awt.Color(255, 255, 255));
        SEMESTER_GROUP.add(SEMESTER2);
        SEMESTER2.setText("2");
        INPUT_CLASS_TIME_P.add(SEMESTER2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        jLabel25.setText("년도");
        INPUT_CLASS_TIME_P.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        INPUT_CLASS_YEAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023" }));
        INPUT_CLASS_YEAR.setSelectedItem(2);
        INPUT_CLASS_YEAR.setToolTipText("");
        INPUT_CLASS_TIME_P.add(INPUT_CLASS_YEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 100, -1));
        INPUT_CLASS_TIME_P.add(INPUT_CLASS_PRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 100, -1));
        INPUT_CLASS_TIME_P.add(INPUT_CLASS_NUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 100, -1));
        INPUT_CLASS_TIME_P.add(INPUT_CLASS_NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 100, -1));
        INPUT_CLASS_TIME_P.add(INPUT_CLASS_DIVISON, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 100, -1));

        jLabel26.setText("강의실");
        INPUT_CLASS_TIME_P.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

        INPUT_TIME_P.add(INPUT_CLASS_TIME_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 664, 440));

        INPUT_SPECIAL_TIME_P.setBackground(new java.awt.Color(255, 255, 255));
        INPUT_SPECIAL_TIME_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel14.setText("특강 및 세미나 시간표 입력");
        INPUT_SPECIAL_TIME_P.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 23, -1, -1));

        INPUT_SEMINAR_MONTH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        INPUT_SEMINAR_MONTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INPUT_SEMINAR_MONTHActionPerformed(evt);
            }
        });
        INPUT_SPECIAL_TIME_P.add(INPUT_SEMINAR_MONTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 100, 20));

        SPECIAL_LAB_918.setBackground(new java.awt.Color(255, 255, 255));
        INPUT_SPECIAL_LAB.add(SPECIAL_LAB_918);
        SPECIAL_LAB_918.setText("918호");
        INPUT_SPECIAL_TIME_P.add(SPECIAL_LAB_918, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));

        SPECIAL_SELECT_DAY_BTN.setBackground(new java.awt.Color(255, 255, 255));
        SPECIAL_SELECT_DAY_BTN.setText("등록");
        SPECIAL_SELECT_DAY_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPECIAL_SELECT_DAY_BTNActionPerformed(evt);
            }
        });
        INPUT_SPECIAL_TIME_P.add(SPECIAL_SELECT_DAY_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 70, -1));

        SPECIAL_LAB_911.setBackground(new java.awt.Color(255, 255, 255));
        INPUT_SPECIAL_LAB.add(SPECIAL_LAB_911);
        SPECIAL_LAB_911.setText("911호");
        INPUT_SPECIAL_TIME_P.add(SPECIAL_LAB_911, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        jLabel24.setText("시작 시간");
        INPUT_SPECIAL_TIME_P.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, 20));

        INPUT_SEMINAR_STIME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00" }));
        INPUT_SPECIAL_TIME_P.add(INPUT_SEMINAR_STIME, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 100, 20));

        jLabel28.setText("종료시간");
        INPUT_SPECIAL_TIME_P.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, 20));

        INPUT_SEMINAR_ETIME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));
        INPUT_SPECIAL_TIME_P.add(INPUT_SEMINAR_ETIME, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 100, 20));

        SPECIAL_LAB_915.setBackground(new java.awt.Color(255, 255, 255));
        INPUT_SPECIAL_LAB.add(SPECIAL_LAB_915);
        SPECIAL_LAB_915.setSelected(true);
        SPECIAL_LAB_915.setText("915호");
        INPUT_SPECIAL_TIME_P.add(SPECIAL_LAB_915, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        SPECIAL_LAB_916.setBackground(new java.awt.Color(255, 255, 255));
        INPUT_SPECIAL_LAB.add(SPECIAL_LAB_916);
        SPECIAL_LAB_916.setText("916호");
        INPUT_SPECIAL_TIME_P.add(SPECIAL_LAB_916, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        INPUT_SEMINAR_YEAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", " " }));
        INPUT_SPECIAL_TIME_P.add(INPUT_SEMINAR_YEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 100, 20));

        INPUT_SPECIAL_TIME_P.add(INPUT_SEMINAR_DATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 100, 20));

        jLabel16.setText("년");
        INPUT_SPECIAL_TIME_P.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 46, 20));

        jLabel17.setText("월");
        INPUT_SPECIAL_TIME_P.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 46, 20));

        jLabel18.setText("일");
        INPUT_SPECIAL_TIME_P.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 46, 20));

        jLabel37.setText("예약자 번호");
        INPUT_SPECIAL_TIME_P.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel38.setText("특강 및 세미나 명");
        INPUT_SPECIAL_TIME_P.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel39.setText("강의실");
        INPUT_SPECIAL_TIME_P.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));
        INPUT_SPECIAL_TIME_P.add(INPUT_SEMINAR_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 100, -1));
        INPUT_SPECIAL_TIME_P.add(INPUT_SEMINAR_NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 100, -1));

        INPUT_TIME_P.add(INPUT_SPECIAL_TIME_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 664, 426));

        MAIN_P.add(INPUT_TIME_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 814, 426));

        RESERVATION_LIST_P.setBackground(new java.awt.Color(255, 255, 255));
        RESERVATION_LIST_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RESERVATION_M_P.setBackground(new java.awt.Color(255, 255, 255));
        RESERVATION_M_P.setPreferredSize(new java.awt.Dimension(100, 426));
        RESERVATION_M_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel10.setText("MENU");
        RESERVATION_M_P.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 41, -1, -1));
        RESERVATION_M_P.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, 110, 10));

        REQUEST_RESER.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        REQUEST_RESER.setText("예약 승인");
        REQUEST_RESER.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        REQUEST_RESER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REQUEST_RESERMouseClicked(evt);
            }
        });
        RESERVATION_M_P.add(REQUEST_RESER, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        USING_HISTORY.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        USING_HISTORY.setText("사용 기록 조회");
        USING_HISTORY.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        USING_HISTORY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                USING_HISTORYMouseClicked(evt);
            }
        });
        RESERVATION_M_P.add(USING_HISTORY, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 120, -1, -1));

        USING_NOW.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        USING_NOW.setText("사용 현황 조회");
        USING_NOW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        USING_NOW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                USING_NOWMouseClicked(evt);
            }
        });
        RESERVATION_M_P.add(USING_NOW, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 150, -1, -1));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        RESERVATION_M_P.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 10, 2, 420));

        RESERVATION_LIST_P.add(RESERVATION_M_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 440));

        USING_NOW_P.setBackground(new java.awt.Color(255, 255, 255));
        USING_NOW_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel19.setText("사용 현황 조회");
        USING_NOW_P.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 22, -1, -1));

        USING_915.setBackground(new java.awt.Color(255, 255, 255));
        USING_NOW_LAB.add(USING_915);
        USING_915.setSelected(true);
        USING_915.setText("915호");
        USING_915.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        USING_NOW_P.add(USING_915, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        USING_916.setBackground(new java.awt.Color(255, 255, 255));
        USING_NOW_LAB.add(USING_916);
        USING_916.setText("916호");
        USING_916.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        USING_NOW_P.add(USING_916, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        USING_918.setBackground(new java.awt.Color(255, 255, 255));
        USING_NOW_LAB.add(USING_918);
        USING_918.setText("918호");
        USING_918.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        USING_NOW_P.add(USING_918, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        USING_911.setBackground(new java.awt.Color(255, 255, 255));
        USING_NOW_LAB.add(USING_911);
        USING_911.setText("911호");
        USING_911.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        USING_NOW_P.add(USING_911, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        NOW_USING_PANEL1.setBackground(new java.awt.Color(255, 255, 255));
        NOW_USING_PANEL1.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        NOW_USING_PANEL1.setLayout(new java.awt.GridLayout(5, 8, 15, 15));
        USING_NOW_P.add(NOW_USING_PANEL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        NOW_USING_PANEL2.setBackground(new java.awt.Color(255, 255, 255));
        NOW_USING_PANEL2.setLayout(new java.awt.GridLayout(5, 4, 15, 15));
        USING_NOW_P.add(NOW_USING_PANEL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        RESERVATION_LIST_P.add(USING_NOW_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 664, 440));

        REQUEST_RESER_P.setBackground(new java.awt.Color(255, 255, 255));

        REQUEST_TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "일시", "강의실", "좌석", "학생명", "조별 활동", "승인 여부"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        REQUEST_TABLE.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane3.setViewportView(REQUEST_TABLE);

        jLabel8.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel8.setText("예약 승인");

        APPROVAL_ALL_BTN.setText("전체 승인");

        APPROVAL_BTN.setText("승인하기");

        javax.swing.GroupLayout REQUEST_RESER_PLayout = new javax.swing.GroupLayout(REQUEST_RESER_P);
        REQUEST_RESER_P.setLayout(REQUEST_RESER_PLayout);
        REQUEST_RESER_PLayout.setHorizontalGroup(
            REQUEST_RESER_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REQUEST_RESER_PLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel8)
                .addContainerGap(287, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, REQUEST_RESER_PLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(APPROVAL_BTN)
                .addGap(18, 18, 18)
                .addComponent(APPROVAL_ALL_BTN)
                .addGap(25, 25, 25))
        );
        REQUEST_RESER_PLayout.setVerticalGroup(
            REQUEST_RESER_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REQUEST_RESER_PLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(REQUEST_RESER_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(APPROVAL_ALL_BTN)
                    .addComponent(APPROVAL_BTN))
                .addGap(24, 24, 24))
        );

        RESERVATION_LIST_P.add(REQUEST_RESER_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 664, 426));

        USING_HISTORY_P.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel11.setText("사용 기록 조회");

        HISTORY_TALBE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "일시", "강의실", "좌석", "학생 명", "조별 활동", "승인 여부"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        HISTORY_TALBE.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        HISTORY_TALBE.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(HISTORY_TALBE);

        javax.swing.GroupLayout USING_HISTORY_PLayout = new javax.swing.GroupLayout(USING_HISTORY_P);
        USING_HISTORY_P.setLayout(USING_HISTORY_PLayout);
        USING_HISTORY_PLayout.setHorizontalGroup(
            USING_HISTORY_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(USING_HISTORY_PLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );
        USING_HISTORY_PLayout.setVerticalGroup(
            USING_HISTORY_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(USING_HISTORY_PLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        RESERVATION_LIST_P.add(USING_HISTORY_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 664, 426));

        MAIN_P.add(RESERVATION_LIST_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 814, -1));

        STU_MANAGEMENT_P.setBackground(new java.awt.Color(255, 255, 255));
        STU_MANAGEMENT_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        STU_M_P.setBackground(new java.awt.Color(255, 255, 255));
        STU_M_P.setPreferredSize(new java.awt.Dimension(100, 426));
        STU_M_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel7.setText("MENU");
        STU_M_P.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 41, -1, -1));
        STU_M_P.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, 110, 10));

        STU_LIST.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        STU_LIST.setText("학생 명단 관리");
        STU_LIST.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        STU_LIST.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                STU_LISTMouseClicked(evt);
            }
        });
        STU_M_P.add(STU_LIST, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        STU_TOKEN.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        STU_TOKEN.setText("토큰 관리");
        STU_TOKEN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        STU_TOKEN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                STU_TOKENMouseClicked(evt);
            }
        });
        STU_M_P.add(STU_TOKEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        STU_M_P.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        STU_M_P.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 10, 2, 420));

        STU_MANAGEMENT_P.add(STU_M_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 426));

        STU_LIST_P.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel9.setText("학생 명단");

        STU_LIST_T.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "학번", "이름", "전화번호", "이메일", "승인 여부"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        STU_LIST_T.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        STU_LIST_T.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(STU_LIST_T);

        jButton1.setText("삭제");

        jButton2.setText("정보 수정");

        javax.swing.GroupLayout STU_LIST_PLayout = new javax.swing.GroupLayout(STU_LIST_P);
        STU_LIST_P.setLayout(STU_LIST_PLayout);
        STU_LIST_PLayout.setHorizontalGroup(
            STU_LIST_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, STU_LIST_PLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(STU_LIST_PLayout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(jLabel9)
                .addContainerGap(270, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        STU_LIST_PLayout.setVerticalGroup(
            STU_LIST_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STU_LIST_PLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(STU_LIST_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        STU_MANAGEMENT_P.add(STU_LIST_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 664, 426));

        STU_TOKEN_P.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel15.setText("토큰 관리");

        TOKEN.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N

        jLabel20.setText("현재 토큰");

        INPUT_TOKEN.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        INPUT_TOKEN.setText("새 토큰 생성하기");

        javax.swing.GroupLayout STU_TOKEN_PLayout = new javax.swing.GroupLayout(STU_TOKEN_P);
        STU_TOKEN_P.setLayout(STU_TOKEN_PLayout);
        STU_TOKEN_PLayout.setHorizontalGroup(
            STU_TOKEN_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STU_TOKEN_PLayout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addGroup(STU_TOKEN_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, STU_TOKEN_PLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(274, 274, 274))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, STU_TOKEN_PLayout.createSequentialGroup()
                        .addGroup(STU_TOKEN_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(STU_TOKEN_PLayout.createSequentialGroup()
                                .addComponent(TOKEN, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(INPUT_TOKEN))
                            .addComponent(jLabel20))
                        .addGap(151, 151, 151))))
        );
        STU_TOKEN_PLayout.setVerticalGroup(
            STU_TOKEN_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STU_TOKEN_PLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(133, 133, 133)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(STU_TOKEN_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(INPUT_TOKEN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TOKEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(206, Short.MAX_VALUE))
        );

        STU_MANAGEMENT_P.add(STU_TOKEN_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 664, 426));

        MAIN_P.add(STU_MANAGEMENT_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, -1, -1));

        M_NOTICE_P.setBackground(new java.awt.Color(255, 255, 255));
        M_NOTICE_P.setVerifyInputWhenFocusTarget(false);
        M_NOTICE_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NOTICE_M_P.setBackground(new java.awt.Color(255, 255, 255));
        NOTICE_M_P.setPreferredSize(new java.awt.Dimension(100, 426));
        NOTICE_M_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel6.setText("MENU");
        NOTICE_M_P.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 41, -1, -1));

        NOTICE_L.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        NOTICE_L.setText("공지사항");
        NOTICE_L.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NOTICE_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NOTICE_LMouseClicked(evt);
            }
        });
        NOTICE_M_P.add(NOTICE_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        Declaration_L.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        Declaration_L.setText("신고 및 문의");
        Declaration_L.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Declaration_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Declaration_LMouseClicked(evt);
            }
        });
        NOTICE_M_P.add(Declaration_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 120, -1, -1));
        NOTICE_M_P.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, 110, 10));
        NOTICE_M_P.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));
        NOTICE_M_P.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 40));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        NOTICE_M_P.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 10, 2, 420));

        M_NOTICE_P.add(NOTICE_M_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 440));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setPreferredSize(new java.awt.Dimension(454, 0));

        NOTICE_LIST.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "날짜", "제목", "작성자", "비고"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        NOTICE_LIST.setGridColor(new java.awt.Color(255, 255, 255));
        NOTICE_LIST.setPreferredSize(new java.awt.Dimension(660, 0));
        NOTICE_LIST.setSelectionBackground(new java.awt.Color(255, 255, 255));
        NOTICE_LIST.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        NOTICE_LIST.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        NOTICE_LIST.setShowGrid(true);
        jScrollPane1.setViewportView(NOTICE_LIST);

        M_NOTICE_P.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 56, 666, 370));

        NOTICE_TITLE.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        NOTICE_TITLE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NOTICE_TITLE.setText("공지사항");
        M_NOTICE_P.add(NOTICE_TITLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 160, -1));

        WRITE.setText("글쓰기");
        WRITE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        WRITE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WRITEMouseClicked(evt);
            }
        });
        M_NOTICE_P.add(WRITE, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, -1));

        CHANGE.setText("수정");
        CHANGE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CHANGE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CHANGEMouseClicked(evt);
            }
        });
        M_NOTICE_P.add(CHANGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));

        DELETE.setText("삭제");
        DELETE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DELETE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETEMouseClicked(evt);
            }
        });
        M_NOTICE_P.add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, -1, -1));

        MAIN_P.add(M_NOTICE_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 440));

        UNDER_P.add(MAIN_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, 470));

        TITLE_P.setBackground(new java.awt.Color(101, 222, 255));
        TITLE_P.setMinimumSize(new java.awt.Dimension(810, 122));
        TITLE_P.setPreferredSize(new java.awt.Dimension(814, 128));
        TITLE_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TITLE.setBackground(new java.awt.Color(0, 0, 0));
        TITLE.setFont(new java.awt.Font("맑은 고딕", 1, 48)); // NOI18N
        TITLE.setText("S.M.P");
        TITLE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TITLE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TITLEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TITLEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TITLEMouseExited(evt);
            }
        });
        TITLE_P.add(TITLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 30, -1, -1));

        LOGOUT.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        LOGOUT.setText("로그아웃");
        LOGOUT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LOGOUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGOUTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LOGOUTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LOGOUTMouseExited(evt);
            }
        });
        TITLE_P.add(LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 102, -1, -1));

        jLabel3.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        jLabel3.setText("님");
        TITLE_P.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 102, -1, -1));

        SNAME.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        SNAME.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SNAME.setText("조교");
        TITLE_P.add(SNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, -1, 40));

        UNDER_P.add(TITLE_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 814, 130));

        getContentPane().add(UNDER_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 815, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TITLEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TITLEMouseClicked
        //타이틀 클릭시 메인 패널로 이동
        panelClear();
        M_NOTICE_P.setVisible(true);
    }//GEN-LAST:event_TITLEMouseClicked

    private void LOGOUTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTMouseClicked
        //로그아웃 버튼 클릭시 로그인 화면으로 이동
        Login l = new Login();
        l.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_LOGOUTMouseClicked

    private void M_MENU4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU4MouseEntered
        // 메뉴 4번 마우스 호버시
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.GRAY);
        jLabel5.setForeground(Color.white);
    }//GEN-LAST:event_M_MENU4MouseEntered

    private void M_MENU4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU4MouseExited
        // 메뉴 4번 마우스 밖으로
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.white);
        jLabel5.setForeground(Color.black);
    }//GEN-LAST:event_M_MENU4MouseExited

    private void M_MENU3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU3MouseEntered
        // 메뉴 3번 마우스 호버시
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.GRAY);
        jLabel4.setForeground(Color.white);
    }//GEN-LAST:event_M_MENU3MouseEntered

    private void M_MENU3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU3MouseExited
        // 메뉴 3번 마우스 밖으로
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.white);
        jLabel4.setForeground(Color.black);
    }//GEN-LAST:event_M_MENU3MouseExited

    private void M_MENU2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU2MouseEntered
        // 메뉴 2번 마우스 호버시
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.GRAY);
        jLabel1.setForeground(Color.white);
    }//GEN-LAST:event_M_MENU2MouseEntered

    private void M_MENU2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU2MouseExited
        // 메뉴 2번 마우스 밖으로
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.white);
        jLabel1.setForeground(Color.black);
    }//GEN-LAST:event_M_MENU2MouseExited

    private void M_MENU1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU1MouseEntered
        // 메뉴 1번 마우스 호버시
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.GRAY);
        jLabel2.setForeground(Color.white);
    }//GEN-LAST:event_M_MENU1MouseEntered

    private void M_MENU1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU1MouseExited
        // 메뉴 1번 마우스 밖으로
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.white);
        jLabel2.setForeground(Color.black);
    }//GEN-LAST:event_M_MENU1MouseExited

    private void LOGOUTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTMouseEntered
        // 로그아웃 호버 시 색 변경
        LOGOUT.setForeground(Color.white);
    }//GEN-LAST:event_LOGOUTMouseEntered

    private void LOGOUTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTMouseExited
        // 로그아웃 마우스 바깥으로
        LOGOUT.setForeground(Color.black);
    }//GEN-LAST:event_LOGOUTMouseExited

    private void TITLEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TITLEMouseEntered
        // 타이틀 호버시 색 변경
        TITLE.setForeground(Color.white);
    }//GEN-LAST:event_TITLEMouseEntered

    private void TITLEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TITLEMouseExited
        // 타이틀 마우스 바깥으로
        TITLE.setForeground(Color.black);
    }//GEN-LAST:event_TITLEMouseExited

    private void M_MENU4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU4MouseClicked
        // 게시판 메뉴 선택시
        // 컨트롤러에 있는 공지사항 목록 출력 함수 사용
        panelClear();
        M_NOTICE_P.setVisible(true);
        NOTICE_TITLE.setText("공지사항");
    }//GEN-LAST:event_M_MENU4MouseClicked

    private void M_MENU3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU3MouseClicked
        //실습실 시간표 입력 메뉴 선택 시
        panelClear();
        INPUT_TIME_P.setVisible(true);
        INPUT_CLASS_TIME_P.setVisible(true);
        INPUT_SPECIAL_TIME_P.setVisible(false);
    }//GEN-LAST:event_M_MENU3MouseClicked

    private void M_MENU2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU2MouseClicked
        // 예약 내역 조회 패널로 이동
        panelClear();
        USING_NOW_P.setVisible(false);
        RESERVATION_LIST_P.setVisible(true);
        USING_HISTORY_P.setVisible(false);
        REQUEST_RESER_P.setVisible(true);
        
        // 컨트롤러에 있는 예약 조회 함수로 테이블 값 채우기
        UseLab_controller uc = new UseLab_controller(this);
        uc.to_m_showReser();
    }//GEN-LAST:event_M_MENU2MouseClicked

    private void M_MENU1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MENU1MouseClicked
        // 학생 명단 관리 패널로 이동
        panelClear();
        STU_MANAGEMENT_P.setVisible(true);
        STU_LIST_P.setVisible(true);
        STU_TOKEN_P.setVisible(false);
        // 컨트롤러에서 예약 신청 테이블 띄워주기
    }//GEN-LAST:event_M_MENU1MouseClicked

    private void DELETEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEMouseClicked
        //리스트에 있는 게시글 삭제(본인 글에 한해서)
        // 컨트롤러에 있는 목록 삭제 함수 사용
    }//GEN-LAST:event_DELETEMouseClicked

    private void CHANGEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CHANGEMouseClicked
        // 글 수정 화면 띄우기(본인 글에 한해서)
        
    }//GEN-LAST:event_CHANGEMouseClicked

    private void WRITEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WRITEMouseClicked
        // 글 작성 화면 띄우기
        ;
    }//GEN-LAST:event_WRITEMouseClicked

    private void Declaration_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Declaration_LMouseClicked
        // 메뉴에 신고 및 문의 클릭시 신고 및 문의 내용 출력
        // 컨트롤러에 있는 신고 및 문의사항 출력 함수 사용
        NOTICE_TITLE.setText("신고 및 문의");
    }//GEN-LAST:event_Declaration_LMouseClicked

    private void NOTICE_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NOTICE_LMouseClicked
        // 메뉴에 공지사항 클릭시 공지사항 내용 출력
        // 컨트롤러에 있는 공지사항 출력 함수 사용
        NOTICE_TITLE.setText("공지사항");
    }//GEN-LAST:event_NOTICE_LMouseClicked

    private void REQUEST_RESERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REQUEST_RESERMouseClicked
        // 예약내역 관리 메뉴 밑 예약 승인 메뉴 클릭시
        USING_HISTORY_P.setVisible(false);
        REQUEST_RESER_P.setVisible(true);
        USING_NOW_P.setVisible(false);
        // 컨트롤러에서 예약 신청 테이블 띄워주기
        UseLab_controller uc = new UseLab_controller(this);
        uc.to_m_showReser();
    }//GEN-LAST:event_REQUEST_RESERMouseClicked

    private void USING_HISTORYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_USING_HISTORYMouseClicked
        // 예약내역 관리 메뉴 밑 사용 기록 메뉴 클릭시
        USING_HISTORY_P.setVisible(true);
        REQUEST_RESER_P.setVisible(false);
        USING_NOW_P.setVisible(false);
        // 컨트롤러에서 사용기록 테이블 띄워주기
        UseLab_controller uc = new UseLab_controller(this);
        uc.m_showReser();
    }//GEN-LAST:event_USING_HISTORYMouseClicked

    private void STU_LISTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STU_LISTMouseClicked
        // 학생 명단 관리 메뉴 밑 학생 명단 관리 메뉴 클릭시
        //토큰관리 패널 false
        STU_LIST_P.setVisible(true);
        // 컨트롤러에서 예약 신청 테이블 띄워주기
        
    }//GEN-LAST:event_STU_LISTMouseClicked

    private void INPUT_CLASSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INPUT_CLASSMouseClicked
        // 실습실 시간표 입력 밑 강의 시간표 입력
        INPUT_CLASS_TIME_P.setVisible(true);
        INPUT_SPECIAL_TIME_P.setVisible(false);
    }//GEN-LAST:event_INPUT_CLASSMouseClicked

    private void INPUT_SPECIALMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INPUT_SPECIALMouseClicked
        // 실습실 시간표 입력 밑 특강 시간표 입력
        INPUT_CLASS_TIME_P.setVisible(false);
        INPUT_SPECIAL_TIME_P.setVisible(true);
        Calendar cal = Calendar.getInstance();
        INPUT_SEMINAR_DATE.removeAll();
        cal.set(Integer.parseInt(INPUT_SEMINAR_YEAR.getSelectedItem().toString()), Integer.parseInt(INPUT_SEMINAR_MONTH.getSelectedItem().toString()), 1);
        for(int i=0; i<cal.getActualMaximum(Calendar.DAY_OF_MONTH);i++ ){
            INPUT_SEMINAR_DATE.addItem(Integer.toString(i+1));
        }
    }//GEN-LAST:event_INPUT_SPECIALMouseClicked

    private void STU_TOKENMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STU_TOKENMouseClicked
        // 학생 명단 관리 밑 토큰 관리
        STU_LIST_P.setVisible(false);
        STU_TOKEN_P.setVisible(true);
    }//GEN-LAST:event_STU_TOKENMouseClicked

    private void USING_NOWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_USING_NOWMouseClicked
        // 현재 사용자 조회
        USING_HISTORY_P.setVisible(false);
        REQUEST_RESER_P.setVisible(false);
        USING_NOW_P.setVisible(true);
        NOW_USING_PANEL1.removeAll();
        NOW_USING_PANEL2.removeAll();
        int co =0;
        int j=0;
        JLabel seat;
        
        for(int i=0; i<40; i++){
            seat = new JLabel("<html><body style='text-align:center;'> "+Integer.toString(i+1)+"<br>"+20183150+"</html>",JLabel.CENTER);
            if(j == 0){
                NOW_USING_PANEL1.add(seat);
            }else if(j == 1){
                NOW_USING_PANEL2.add(seat);
            }
            if( co%4 == 3 ){
                if(j==0){
                    j = 1;
                }else if (j == 1){
                    j=0;
                }
            }
            co++; 
        }
        
        
    }//GEN-LAST:event_USING_NOWMouseClicked

    private void CLASS_SELECT_DAY_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLASS_SELECT_DAY_BTNActionPerformed
        // 강의 등록 버튼 클릭시
       // Timetable_controller time = new Timetable_controller();
        //time.insertClass();
    }//GEN-LAST:event_CLASS_SELECT_DAY_BTNActionPerformed

    private void SPECIAL_SELECT_DAY_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPECIAL_SELECT_DAY_BTNActionPerformed
        // 특강 및 세미나 등록 버튼 클릭시
        //Timetable_controller time = new Timetable_controller();
       // time.insertSeminar();
    }//GEN-LAST:event_SPECIAL_SELECT_DAY_BTNActionPerformed

    private void INPUT_SEMINAR_MONTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INPUT_SEMINAR_MONTHActionPerformed
        // 특강입력 월 선택시 해당 일 수 반영
        Calendar cal = Calendar.getInstance();
        INPUT_SEMINAR_DATE.removeAllItems();
        cal.set(Integer.parseInt(INPUT_SEMINAR_YEAR.getSelectedItem().toString()), Integer.parseInt(INPUT_SEMINAR_MONTH.getSelectedItem().toString())-1, 1);
        System.out.println(cal.getActualMaximum(Calendar.DAY_OF_MONTH));
        for(int i=0; i<cal.getActualMaximum(Calendar.DAY_OF_MONTH);i++ ){
            INPUT_SEMINAR_DATE.addItem(Integer.toString(i+1));
        }
    }//GEN-LAST:event_INPUT_SEMINAR_MONTHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton APPROVAL_ALL_BTN;
    private javax.swing.JButton APPROVAL_BTN;
    private javax.swing.JLabel CHANGE;
    private javax.swing.JRadioButton CLASS_LAB_911;
    public javax.swing.JRadioButton CLASS_LAB_915;
    public javax.swing.JRadioButton CLASS_LAB_916;
    public javax.swing.JRadioButton CLASS_LAB_918;
    public javax.swing.JButton CLASS_SELECT_DAY_BTN;
    private javax.swing.JLabel DELETE;
    private javax.swing.JLabel Declaration_L;
    public javax.swing.JTable HISTORY_TALBE;
    private javax.swing.JLabel INPUT_CLASS;
    public javax.swing.JComboBox<String> INPUT_CLASS_DAY;
    public javax.swing.JTextField INPUT_CLASS_DIVISON;
    public javax.swing.JComboBox<String> INPUT_CLASS_ETIME;
    public javax.swing.ButtonGroup INPUT_CLASS_LAB;
    public javax.swing.JTextField INPUT_CLASS_NAME;
    public javax.swing.JTextField INPUT_CLASS_NUM;
    public javax.swing.JTextField INPUT_CLASS_PRO;
    public javax.swing.JComboBox<String> INPUT_CLASS_STIME;
    private javax.swing.JPanel INPUT_CLASS_TIME_P;
    public javax.swing.JComboBox<String> INPUT_CLASS_YEAR;
    private javax.swing.JPanel INPUT_M_P;
    public javax.swing.JComboBox<String> INPUT_SEMINAR_DATE;
    public javax.swing.JComboBox<String> INPUT_SEMINAR_ETIME;
    public javax.swing.JTextField INPUT_SEMINAR_ID;
    public javax.swing.JComboBox<String> INPUT_SEMINAR_MONTH;
    public javax.swing.JTextField INPUT_SEMINAR_NAME;
    public javax.swing.JComboBox<String> INPUT_SEMINAR_STIME;
    public javax.swing.JComboBox<String> INPUT_SEMINAR_YEAR;
    private javax.swing.JLabel INPUT_SPECIAL;
    private javax.swing.ButtonGroup INPUT_SPECIAL_LAB;
    public javax.swing.JPanel INPUT_SPECIAL_TIME_P;
    private javax.swing.JPanel INPUT_TIME_P;
    private javax.swing.JButton INPUT_TOKEN;
    private javax.swing.JLabel LOGOUT;
    private javax.swing.JPanel MAIN_P;
    private javax.swing.JPanel M_MENU1;
    private javax.swing.JPanel M_MENU2;
    private javax.swing.JPanel M_MENU3;
    private javax.swing.JPanel M_MENU4;
    private javax.swing.JPanel M_MENU_P;
    private javax.swing.JPanel M_NOTICE_P;
    private javax.swing.JLabel NOTICE_L;
    private javax.swing.JTable NOTICE_LIST;
    private javax.swing.JPanel NOTICE_M_P;
    private javax.swing.JLabel NOTICE_TITLE;
    private javax.swing.JPanel NOW_USING_PANEL1;
    private javax.swing.JPanel NOW_USING_PANEL2;
    private javax.swing.JLabel REQUEST_RESER;
    private javax.swing.JPanel REQUEST_RESER_P;
    public javax.swing.JTable REQUEST_TABLE;
    private javax.swing.JPanel RESERVATION_LIST_P;
    private javax.swing.JPanel RESERVATION_M_P;
    public javax.swing.JRadioButton SEMESTER1;
    private javax.swing.JRadioButton SEMESTER2;
    public javax.swing.ButtonGroup SEMESTER_GROUP;
    public javax.swing.JLabel SNAME;
    public javax.swing.JRadioButton SPECIAL_LAB_911;
    public javax.swing.JRadioButton SPECIAL_LAB_915;
    public javax.swing.JRadioButton SPECIAL_LAB_916;
    public javax.swing.JRadioButton SPECIAL_LAB_918;
    private javax.swing.JButton SPECIAL_SELECT_DAY_BTN;
    private javax.swing.JLabel STU_LIST;
    private javax.swing.JPanel STU_LIST_P;
    private javax.swing.JTable STU_LIST_T;
    private javax.swing.JPanel STU_MANAGEMENT_P;
    private javax.swing.JPanel STU_M_P;
    private javax.swing.JLabel STU_TOKEN;
    private javax.swing.JPanel STU_TOKEN_P;
    private javax.swing.JLabel TITLE;
    private javax.swing.JPanel TITLE_P;
    private javax.swing.JTextField TOKEN;
    private javax.swing.JPanel UNDER_P;
    private javax.swing.JRadioButton USING_911;
    private javax.swing.JRadioButton USING_915;
    private javax.swing.JRadioButton USING_916;
    private javax.swing.JRadioButton USING_918;
    private javax.swing.JLabel USING_HISTORY;
    private javax.swing.JPanel USING_HISTORY_P;
    private javax.swing.JLabel USING_NOW;
    private javax.swing.ButtonGroup USING_NOW_LAB;
    private javax.swing.JPanel USING_NOW_P;
    private javax.swing.JLabel WRITE;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
