/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.MemberManage_controller;
import Controller.ReserLab_controller;
import Controller.UseLab_controller;
import java.awt.Color;
import java.awt.Font;
import java.awt.Label;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author 20183150 김부성
 * 클래스 사용 용도 : 학생 화면 제작 클래스
 */
public class Student_Main extends javax.swing.JFrame {

    /**
     * Creates new form Student_Main
     */
    public Student_Main() {
        initComponents();
        panelClear();
        S_NOTICE_P.setVisible(true); //초기 메인 화면 출력
    }
    
    public void panelClear(){ // 모든 패널을 지우는 함수
        S_NOTICE_P.setVisible(false);
        NOTICE_INPUT_BTN.setVisible(false);
        NOTICE_CHANGE_BTN.setVisible(false);
        NOTICE_DEL_BTN.setVisible(false);
        S_MYPAGE_P.setVisible(false);
        S_INQUIRY_P.setVisible(false);
        S_RESERVATION_P.setVisible(false);
    }
    
    public String getChangeName(){ //변경할 이름
        return CHANGE_NAME.getText();
    }
    
    public String getChangeEmail(){ //변경할 이메일
        return CHANGE_EMAIL.getText();
    }
    
    public String getChangePhone(){ //변경할 전화번호
        return CHANGE_PHONE.getText();
    }
    
    public String getNowPw() { // 현재 비밀번호
        String nowpw = new String(NOW_PW.getPassword());
        return nowpw;
    }

    public String getChangePw() { //변경할 비밀번호
        String changepw = new String(CHANGE_PW.getPassword());
        return changepw;
    }
    public String getEndtime(){ //종료 시간
        return (String) STU_RESER_ETIME.getSelectedItem();
    }
    
    public String getStartTime(){ //시작 시간
        return (String) STU_RESER_STIME.getSelectedItem();      
    }
    
    public String getLabNum(){ // 예약 강의실 선택 값 받아오는 함수
        String lab = null;
        if(LAB_915.isSelected())
            lab = LAB_915.getText();
        else if(LAB_916.isSelected())
            lab = LAB_916.getText();
        else if(LAB_918.isSelected())
            lab = LAB_918.getText();
        else if(LAB_911.isSelected())
            lab = LAB_911.getText();
        return lab;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        INQUIRY_DIALOG = new javax.swing.JDialog();
        INQUIRY_P = new javax.swing.JPanel();
        INQUIRY_TITLE = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        INPUT_INQUIRY_TITLE1 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        INPUT_INQUIRY_CONTENT1 = new javax.swing.JTextArea();
        EXIT_INQUIRY_BTN = new javax.swing.JButton();
        INPUT_INQUIRY_BTN = new javax.swing.JButton();
        CHANGE_INQUIRY_BTN = new javax.swing.JButton();
        REPORT_RADIO = new javax.swing.JRadioButton();
        INQUIRY_RADIO = new javax.swing.JRadioButton();
        NOTICE_INFO = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        NOTICE_WRITER_L = new javax.swing.JLabel();
        NOTICE_NYM_L = new javax.swing.JLabel();
        TITLE_F = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TEXT_F = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        INQUIRY_GROUP = new javax.swing.ButtonGroup();
        UNDER_P = new javax.swing.JPanel();
        MAIN_P = new javax.swing.JPanel();
        S_MENU_P = new javax.swing.JPanel();
        S_MENU2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        S_MENU3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        S_MENU4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        S_MENU1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        S_MYPAGE_P = new javax.swing.JPanel();
        S_MY_MENU_P = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CHANGE_NUMBER = new javax.swing.JTextField();
        CHANGE_NAME = new javax.swing.JTextField();
        CHANGE_EMAIL = new javax.swing.JTextField();
        CHANGE_PHONE = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        NOW_PW = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        CHANGE_PW = new javax.swing.JPasswordField();
        INFO_CHANGE_BTN = new javax.swing.JButton();
        INFO_DEL_BTN = new javax.swing.JButton();
        S_NOTICE_P = new javax.swing.JPanel();
        S_NOTICE_M_P = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        NOTICE_L = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        NOTICE_INQUIRY_L = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        NOTICE_LIST = new javax.swing.JTable();
        NOTICE_TITLE = new javax.swing.JLabel();
        NOTICE_CHECK_BTN = new javax.swing.JButton();
        NOTICE_INPUT_BTN = new javax.swing.JButton();
        NOTICE_CHANGE_BTN = new javax.swing.JButton();
        NOTICE_DEL_BTN = new javax.swing.JButton();
        S_RESERVATION_P = new javax.swing.JPanel();
        S_RESER_MENU_P = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        SELECT_RE_INFO = new javax.swing.JPanel();
        CALENDAR_P = new javax.swing.JPanel();
        YEAR_L = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        MONTH_L = new javax.swing.JLabel();
        RIGHT_L = new javax.swing.JLabel();
        LEFT_L = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        DATE_P = new javax.swing.JPanel();
        LAB_915 = new javax.swing.JRadioButton();
        LAB_916 = new javax.swing.JRadioButton();
        LAB_918 = new javax.swing.JRadioButton();
        LAB_911 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        SET_DATE_L = new javax.swing.JLabel();
        TEAM_CHECK = new javax.swing.JCheckBox();
        INPUT_TEAM = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        TEAM_1 = new javax.swing.JTextField();
        TEAM_2 = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        TEAM_3 = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        TEAM_SEAT1_F = new javax.swing.JTextField();
        TEAM_SEAT2_F = new javax.swing.JTextField();
        TEAM_SEAT3_F = new javax.swing.JTextField();
        SEARCH_CUR_BTN = new javax.swing.JButton();
        STU_RESER_ETIME = new javax.swing.JComboBox<>();
        STU_RESER_STIME = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        SEAT_P = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        SEAT_F = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        S_INQUIRY_P = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        INQUIRY_L = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        RESERVATION_TABLE = new javax.swing.JTable();
        DELETE_RE_BTN = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        TITLE_P = new javax.swing.JPanel();
        TITLE = new javax.swing.JLabel();
        LOGOUT = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        STU_NUM = new javax.swing.JLabel();

        INQUIRY_DIALOG.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        INQUIRY_DIALOG.setTitle("문의 사항");
        INQUIRY_DIALOG.setBackground(new java.awt.Color(255, 255, 255));
        INQUIRY_DIALOG.setLocation(new java.awt.Point(100, 100));
        INQUIRY_DIALOG.setResizable(false);
        INQUIRY_DIALOG.setSize(new java.awt.Dimension(400, 430));

        INQUIRY_P.setBackground(new java.awt.Color(255, 255, 255));
        INQUIRY_P.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        INQUIRY_P.setPreferredSize(new java.awt.Dimension(400, 430));
        INQUIRY_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        INQUIRY_TITLE.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        INQUIRY_TITLE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        INQUIRY_TITLE.setText("등록하기");
        INQUIRY_P.add(INQUIRY_TITLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 110, -1));

        jLabel42.setText("제목");
        INQUIRY_P.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));
        INQUIRY_P.add(INPUT_INQUIRY_TITLE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 300, -1));

        jLabel43.setText("내용");
        INQUIRY_P.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        INPUT_INQUIRY_CONTENT1.setColumns(20);
        INPUT_INQUIRY_CONTENT1.setRows(5);
        INPUT_INQUIRY_CONTENT1.setTabSize(4);
        jScrollPane5.setViewportView(INPUT_INQUIRY_CONTENT1);

        INQUIRY_P.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 300, 200));

        EXIT_INQUIRY_BTN.setText("닫기");
        EXIT_INQUIRY_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXIT_INQUIRY_BTNActionPerformed(evt);
            }
        });
        INQUIRY_P.add(EXIT_INQUIRY_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 60, -1));

        INPUT_INQUIRY_BTN.setText("등록");
        INQUIRY_P.add(INPUT_INQUIRY_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 60, -1));

        CHANGE_INQUIRY_BTN.setText("수정");
        INQUIRY_P.add(CHANGE_INQUIRY_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 60, -1));

        REPORT_RADIO.setBackground(new java.awt.Color(255, 255, 255));
        INQUIRY_GROUP.add(REPORT_RADIO);
        REPORT_RADIO.setText("신고");
        INQUIRY_P.add(REPORT_RADIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        INQUIRY_RADIO.setBackground(new java.awt.Color(255, 255, 255));
        INQUIRY_GROUP.add(INQUIRY_RADIO);
        INQUIRY_RADIO.setText("문의");
        INQUIRY_P.add(INQUIRY_RADIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        javax.swing.GroupLayout INQUIRY_DIALOGLayout = new javax.swing.GroupLayout(INQUIRY_DIALOG.getContentPane());
        INQUIRY_DIALOG.getContentPane().setLayout(INQUIRY_DIALOGLayout);
        INQUIRY_DIALOGLayout.setHorizontalGroup(
            INQUIRY_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(INQUIRY_P, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        INQUIRY_DIALOGLayout.setVerticalGroup(
            INQUIRY_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(INQUIRY_P, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        NOTICE_INFO.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        NOTICE_INFO.setTitle("공지 사항");
        NOTICE_INFO.setBackground(new java.awt.Color(255, 255, 255));
        NOTICE_INFO.setLocation(new java.awt.Point(100, 100));
        NOTICE_INFO.setModal(true);
        NOTICE_INFO.setResizable(false);
        NOTICE_INFO.setSize(new java.awt.Dimension(430, 450));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(430, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("공지사항");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 110, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 120, 400, -1));

        jLabel29.setText("작성자 : ");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        NOTICE_WRITER_L.setText("관리자");
        jPanel1.add(NOTICE_WRITER_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 60, 70, -1));

        NOTICE_NYM_L.setText("번호");
        jPanel1.add(NOTICE_NYM_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 40, -1));

        TITLE_F.setEditable(false);
        jPanel1.add(TITLE_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 300, -1));

        TEXT_F.setEditable(false);
        TEXT_F.setColumns(20);
        TEXT_F.setRows(5);
        jScrollPane3.setViewportView(TEXT_F);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 390, 240));

        jButton2.setText("닫기");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, -1));

        javax.swing.GroupLayout NOTICE_INFOLayout = new javax.swing.GroupLayout(NOTICE_INFO.getContentPane());
        NOTICE_INFO.getContentPane().setLayout(NOTICE_INFOLayout);
        NOTICE_INFOLayout.setHorizontalGroup(
            NOTICE_INFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        NOTICE_INFOLayout.setVerticalGroup(
            NOTICE_INFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("실습실 관리 시스템");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UNDER_P.setMinimumSize(new java.awt.Dimension(814, 590));
        UNDER_P.setPreferredSize(new java.awt.Dimension(815, 600));
        UNDER_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MAIN_P.setBackground(new java.awt.Color(255, 255, 255));
        MAIN_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        S_MENU_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        S_MENU2.setBackground(new java.awt.Color(255, 255, 255));
        S_MENU2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        S_MENU2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        S_MENU2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        S_MENU2.setPreferredSize(new java.awt.Dimension(204, 3));
        S_MENU2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S_MENU2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                S_MENU2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                S_MENU2MouseExited(evt);
            }
        });
        S_MENU2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("예약 내역 조회");
        S_MENU2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 34));

        S_MENU_P.add(S_MENU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 0, 204, 35));

        S_MENU3.setBackground(new java.awt.Color(255, 255, 255));
        S_MENU3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        S_MENU3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        S_MENU3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S_MENU3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                S_MENU3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                S_MENU3MouseExited(evt);
            }
        });
        S_MENU3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("마이페이지");
        S_MENU3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 34));

        S_MENU_P.add(S_MENU3, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 0, 204, 35));

        S_MENU4.setBackground(new java.awt.Color(255, 255, 255));
        S_MENU4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        S_MENU4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        S_MENU4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S_MENU4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                S_MENU4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                S_MENU4MouseExited(evt);
            }
        });
        S_MENU4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("게시판");
        S_MENU4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 34));

        S_MENU_P.add(S_MENU4, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 0, 204, 35));

        S_MENU1.setBackground(new java.awt.Color(255, 255, 255));
        S_MENU1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        S_MENU1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        S_MENU1.setPreferredSize(new java.awt.Dimension(204, 34));
        S_MENU1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S_MENU1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                S_MENU1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                S_MENU1MouseExited(evt);
            }
        });
        S_MENU1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("실습실 예약");
        S_MENU1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 34));

        S_MENU_P.add(S_MENU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 204, 35));

        MAIN_P.add(S_MENU_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 815, 34));

        S_MYPAGE_P.setBackground(new java.awt.Color(255, 255, 255));
        S_MYPAGE_P.setPreferredSize(new java.awt.Dimension(815, 436));
        S_MYPAGE_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        S_MY_MENU_P.setBackground(new java.awt.Color(255, 255, 255));
        S_MY_MENU_P.setPreferredSize(new java.awt.Dimension(150, 436));
        S_MY_MENU_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel7.setText("MENU");
        S_MY_MENU_P.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 41, -1, -1));

        jLabel8.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        jLabel8.setText("개인 정보 수정");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        S_MY_MENU_P.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 90, -1, -1));
        S_MY_MENU_P.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 150, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        S_MY_MENU_P.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, 110, 10));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        S_MY_MENU_P.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 10, 2, 420));

        S_MYPAGE_P.add(S_MY_MENU_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 436));

        jLabel10.setText("학번");
        S_MYPAGE_P.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jLabel11.setText("이름");
        S_MYPAGE_P.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        jLabel12.setText("이메일");
        S_MYPAGE_P.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        jLabel13.setText("전화번호");
        S_MYPAGE_P.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        jLabel14.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel14.setText("개인 정보 수정");
        S_MYPAGE_P.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 30, -1, -1));

        CHANGE_NUMBER.setEditable(false);
        S_MYPAGE_P.add(CHANGE_NUMBER, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 100, -1));

        CHANGE_NAME.setEditable(false);
        S_MYPAGE_P.add(CHANGE_NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 100, -1));
        S_MYPAGE_P.add(CHANGE_EMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 180, -1));
        S_MYPAGE_P.add(CHANGE_PHONE, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 180, -1));

        jLabel15.setText("현재 비밀번호");
        S_MYPAGE_P.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, -1, -1));
        S_MYPAGE_P.add(NOW_PW, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 150, -1));

        jLabel16.setText("변경된 비밀번호");
        S_MYPAGE_P.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, -1, -1));
        S_MYPAGE_P.add(CHANGE_PW, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 150, -1));

        INFO_CHANGE_BTN.setText("변경하기");
        INFO_CHANGE_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INFO_CHANGE_BTNActionPerformed(evt);
            }
        });
        S_MYPAGE_P.add(INFO_CHANGE_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, -1, -1));

        INFO_DEL_BTN.setText("탈퇴하기");
        INFO_DEL_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INFO_DEL_BTNActionPerformed(evt);
            }
        });
        S_MYPAGE_P.add(INFO_DEL_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, -1, -1));

        MAIN_P.add(S_MYPAGE_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 815, 436));

        S_NOTICE_P.setBackground(new java.awt.Color(255, 255, 255));
        S_NOTICE_P.setPreferredSize(new java.awt.Dimension(815, 436));
        S_NOTICE_P.setVerifyInputWhenFocusTarget(false);
        S_NOTICE_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        S_NOTICE_M_P.setBackground(new java.awt.Color(255, 255, 255));
        S_NOTICE_M_P.setPreferredSize(new java.awt.Dimension(100, 426));
        S_NOTICE_M_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel6.setText("MENU");
        S_NOTICE_M_P.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 41, -1, -1));

        NOTICE_L.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        NOTICE_L.setText("공지사항");
        NOTICE_L.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NOTICE_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NOTICE_LMouseClicked(evt);
            }
        });
        S_NOTICE_M_P.add(NOTICE_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 90, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        S_NOTICE_M_P.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, 110, 10));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        S_NOTICE_M_P.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 10, 2, 420));

        NOTICE_INQUIRY_L.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        NOTICE_INQUIRY_L.setText("신고 및문의");
        NOTICE_INQUIRY_L.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NOTICE_INQUIRY_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NOTICE_INQUIRY_LMouseClicked(evt);
            }
        });
        S_NOTICE_M_P.add(NOTICE_INQUIRY_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        S_NOTICE_P.add(S_NOTICE_M_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 436));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setPreferredSize(new java.awt.Dimension(454, 0));

        NOTICE_LIST.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "날짜", "제목", "작성자", "비고"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        NOTICE_LIST.setGridColor(new java.awt.Color(255, 255, 255));
        NOTICE_LIST.setPreferredSize(new java.awt.Dimension(660, 0));
        NOTICE_LIST.setSelectionBackground(new java.awt.Color(255, 255, 255));
        NOTICE_LIST.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        NOTICE_LIST.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        NOTICE_LIST.setShowGrid(true);
        jScrollPane1.setViewportView(NOTICE_LIST);

        S_NOTICE_P.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 56, 660, 300));

        NOTICE_TITLE.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        NOTICE_TITLE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NOTICE_TITLE.setText("공지사항");
        S_NOTICE_P.add(NOTICE_TITLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 30, 160, -1));

        NOTICE_CHECK_BTN.setText("확인");
        NOTICE_CHECK_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOTICE_CHECK_BTNActionPerformed(evt);
            }
        });
        S_NOTICE_P.add(NOTICE_CHECK_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 25, -1, -1));

        NOTICE_INPUT_BTN.setText("등록");
        NOTICE_INPUT_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOTICE_INPUT_BTNActionPerformed(evt);
            }
        });
        S_NOTICE_P.add(NOTICE_INPUT_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, -1, -1));

        NOTICE_CHANGE_BTN.setText("수정");
        NOTICE_CHANGE_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOTICE_CHANGE_BTNActionPerformed(evt);
            }
        });
        S_NOTICE_P.add(NOTICE_CHANGE_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, -1, -1));

        NOTICE_DEL_BTN.setText("삭제");
        NOTICE_DEL_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOTICE_DEL_BTNActionPerformed(evt);
            }
        });
        S_NOTICE_P.add(NOTICE_DEL_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, -1, -1));

        MAIN_P.add(S_NOTICE_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 815, 436));

        S_RESERVATION_P.setBackground(new java.awt.Color(255, 255, 255));
        S_RESERVATION_P.setPreferredSize(new java.awt.Dimension(815, 436));
        S_RESERVATION_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        S_RESER_MENU_P.setBackground(new java.awt.Color(255, 255, 255));
        S_RESER_MENU_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        S_RESER_MENU_P.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, 110, 10));

        jLabel19.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel19.setText("MENU");
        S_RESER_MENU_P.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 41, -1, -1));

        jLabel20.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        jLabel20.setText("실습실 예약");
        S_RESER_MENU_P.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 90, -1, -1));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        S_RESER_MENU_P.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 10, 2, 420));

        S_RESERVATION_P.add(S_RESER_MENU_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 436));

        jLabel21.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel21.setText("실습실 예약");
        S_RESERVATION_P.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        SELECT_RE_INFO.setBackground(new java.awt.Color(255, 255, 255));
        SELECT_RE_INFO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CALENDAR_P.setBackground(new java.awt.Color(245, 245, 245));
        CALENDAR_P.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CALENDAR_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        YEAR_L.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        YEAR_L.setText("2022");
        CALENDAR_P.add(YEAR_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 30, -1));

        jLabel23.setText("-");
        CALENDAR_P.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 9, -1, -1));

        MONTH_L.setText("11");
        CALENDAR_P.add(MONTH_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        RIGHT_L.setText("▶");
        RIGHT_L.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RIGHT_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RIGHT_LMouseClicked(evt);
            }
        });
        CALENDAR_P.add(RIGHT_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        LEFT_L.setText("◀");
        LEFT_L.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LEFT_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LEFT_LMouseClicked(evt);
            }
        });
        CALENDAR_P.add(LEFT_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel38.setText("월");
        CALENDAR_P.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel39.setText("화");
        CALENDAR_P.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel40.setText("수");
        CALENDAR_P.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel41.setText("목");
        CALENDAR_P.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        jLabel44.setText("금");
        CALENDAR_P.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jLabel45.setForeground(new java.awt.Color(0, 0, 255));
        jLabel45.setText("토");
        CALENDAR_P.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel46.setForeground(java.awt.Color.red);
        jLabel46.setText("일");
        CALENDAR_P.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));
        CALENDAR_P.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 60, 240, -1));

        DATE_P.setBackground(new java.awt.Color(245, 245, 245));
        DATE_P.setLayout(new java.awt.GridLayout(0, 7, 17, 17));
        CALENDAR_P.add(DATE_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        SELECT_RE_INFO.add(CALENDAR_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 270, 270));

        LAB_915.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(LAB_915);
        LAB_915.setText("915호");
        SELECT_RE_INFO.add(LAB_915, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 60, -1));

        LAB_916.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(LAB_916);
        LAB_916.setText("916호");
        SELECT_RE_INFO.add(LAB_916, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 60, -1));

        LAB_918.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(LAB_918);
        LAB_918.setText("918호");
        SELECT_RE_INFO.add(LAB_918, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 60, -1));

        LAB_911.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(LAB_911);
        LAB_911.setText("911호");
        SELECT_RE_INFO.add(LAB_911, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 60, -1));
        SELECT_RE_INFO.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        jLabel25.setFont(new java.awt.Font("굴림", 1, 15)); // NOI18N
        jLabel25.setText("날짜");
        SELECT_RE_INFO.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel26.setFont(new java.awt.Font("굴림", 1, 15)); // NOI18N
        jLabel26.setText("강의실");
        SELECT_RE_INFO.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));
        SELECT_RE_INFO.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 92, 480, 0));

        SET_DATE_L.setFont(new java.awt.Font("굴림", 0, 15)); // NOI18N
        SET_DATE_L.setText("선택하기");
        SET_DATE_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SET_DATE_LMouseClicked(evt);
            }
        });
        SELECT_RE_INFO.add(SET_DATE_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        TEAM_CHECK.setBackground(new java.awt.Color(255, 255, 255));
        TEAM_CHECK.setText("조별 학습");
        TEAM_CHECK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TEAM_CHECK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEAM_CHECKActionPerformed(evt);
            }
        });
        SELECT_RE_INFO.add(TEAM_CHECK, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        INPUT_TEAM.setBackground(new java.awt.Color(255, 255, 255));

        jLabel75.setText("팀원");

        jLabel72.setText("팀원1");

        jLabel73.setText("팀원2");

        jLabel74.setText("팀원3");

        jLabel76.setFont(new java.awt.Font("굴림", 0, 10)); // NOI18N
        jLabel76.setText("(학번만 작성해 주시기 바랍니다.)");

        jLabel30.setText("좌석1");

        jLabel31.setText("좌석3");

        jLabel32.setText("좌석2");

        javax.swing.GroupLayout INPUT_TEAMLayout = new javax.swing.GroupLayout(INPUT_TEAM);
        INPUT_TEAM.setLayout(INPUT_TEAMLayout);
        INPUT_TEAMLayout.setHorizontalGroup(
            INPUT_TEAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(INPUT_TEAMLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(INPUT_TEAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(INPUT_TEAMLayout.createSequentialGroup()
                        .addGroup(INPUT_TEAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(INPUT_TEAMLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel73))
                            .addComponent(jLabel75))
                        .addGap(282, 282, 282)
                        .addComponent(jLabel76))
                    .addGroup(INPUT_TEAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(INPUT_TEAMLayout.createSequentialGroup()
                            .addComponent(jLabel74)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel31))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, INPUT_TEAMLayout.createSequentialGroup()
                            .addComponent(jLabel72)
                            .addGap(57, 57, 57)
                            .addGroup(INPUT_TEAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel32)
                                .addComponent(jLabel30))))
                    .addGroup(INPUT_TEAMLayout.createSequentialGroup()
                        .addComponent(TEAM_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TEAM_SEAT1_F, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(INPUT_TEAMLayout.createSequentialGroup()
                        .addComponent(TEAM_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TEAM_SEAT2_F, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(INPUT_TEAMLayout.createSequentialGroup()
                        .addComponent(TEAM_3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TEAM_SEAT3_F, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        INPUT_TEAMLayout.setVerticalGroup(
            INPUT_TEAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(INPUT_TEAMLayout.createSequentialGroup()
                .addGroup(INPUT_TEAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel75)
                    .addComponent(jLabel76))
                .addGap(5, 5, 5)
                .addGroup(INPUT_TEAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(INPUT_TEAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEAM_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEAM_SEAT1_F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(INPUT_TEAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel73)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(INPUT_TEAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEAM_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEAM_SEAT2_F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(INPUT_TEAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel74)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(INPUT_TEAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEAM_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEAM_SEAT3_F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        SELECT_RE_INFO.add(INPUT_TEAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 15, 180, 190));

        SEARCH_CUR_BTN.setLabel("조회하기");
        SEARCH_CUR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCH_CUR_BTNActionPerformed(evt);
            }
        });
        SELECT_RE_INFO.add(SEARCH_CUR_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, -1));

        STU_RESER_ETIME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", " " }));
        SELECT_RE_INFO.add(STU_RESER_ETIME, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        STU_RESER_STIME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", " " }));
        SELECT_RE_INFO.add(STU_RESER_STIME, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        jLabel22.setFont(new java.awt.Font("굴림", 1, 15)); // NOI18N
        jLabel22.setText("시작");
        SELECT_RE_INFO.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jLabel27.setFont(new java.awt.Font("굴림", 1, 15)); // NOI18N
        jLabel27.setText("종료");
        SELECT_RE_INFO.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        SEAT_P.setBackground(new java.awt.Color(255, 255, 255));
        SEAT_P.setLayout(new java.awt.GridLayout(5, 8, 10, 10));
        SELECT_RE_INFO.add(SEAT_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 380, 250));

        jLabel33.setText("예약 좌석");
        SELECT_RE_INFO.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, -1));
        SELECT_RE_INFO.add(SEAT_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 80, -1));

        jButton3.setText("예약하기");
        SELECT_RE_INFO.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, -1, -1));

        S_RESERVATION_P.add(SELECT_RE_INFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 664, 360));

        MAIN_P.add(S_RESERVATION_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 815, 436));

        S_INQUIRY_P.setBackground(new java.awt.Color(255, 255, 255));
        S_INQUIRY_P.setPreferredSize(new java.awt.Dimension(815, 436));
        S_INQUIRY_P.setVerifyInputWhenFocusTarget(false);
        S_INQUIRY_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, 110, 10));

        jLabel17.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel17.setText("MENU");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 41, -1, -1));

        INQUIRY_L.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        INQUIRY_L.setText("예약 내역 조회");
        INQUIRY_L.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(INQUIRY_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 90, -1, -1));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 10, 2, 420));

        S_INQUIRY_P.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 436));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(664, 320));

        RESERVATION_TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "날짜", "강의실", "시작 시간", "종료 시간", "예약 상태"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        RESERVATION_TABLE.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        RESERVATION_TABLE.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(RESERVATION_TABLE);

        S_INQUIRY_P.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 56, 660, 300));

        DELETE_RE_BTN.setText("취소하기");
        DELETE_RE_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETE_RE_BTNActionPerformed(evt);
            }
        });
        S_INQUIRY_P.add(DELETE_RE_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, -1, -1));

        jLabel18.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel18.setText("예약 내역 조회");
        S_INQUIRY_P.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 30, -1, -1));

        MAIN_P.add(S_INQUIRY_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 815, 436));

        UNDER_P.add(MAIN_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 815, 470));

        TITLE_P.setBackground(new java.awt.Color(101, 222, 255));
        TITLE_P.setMinimumSize(new java.awt.Dimension(810, 122));
        TITLE_P.setPreferredSize(new java.awt.Dimension(815, 130));
        TITLE_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TITLE.setFont(new java.awt.Font("맑은 고딕", 1, 48)); // NOI18N
        TITLE.setText("S.M.P");
        TITLE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TITLE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TITLEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TITLEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TITLEMouseExited(evt);
            }
        });
        TITLE_P.add(TITLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 40, -1, 50));

        LOGOUT.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        LOGOUT.setText("로그아웃");
        LOGOUT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LOGOUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGOUTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LOGOUTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LOGOUTMouseExited(evt);
            }
        });
        TITLE_P.add(LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        jLabel3.setText("님");
        TITLE_P.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, -1, -1));

        STU_NUM.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        STU_NUM.setText("20183109");
        TITLE_P.add(STU_NUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, -1, -1));

        UNDER_P.add(TITLE_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 815, 130));

        getContentPane().add(UNDER_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 815, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TITLEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TITLEMouseClicked
        //타이틀 클릭시 메인 패널로 이동
        S_NOTICE_P.setVisible(true);
        NOTICE_INPUT_BTN.setVisible(false);
        NOTICE_CHANGE_BTN.setVisible(false);
        NOTICE_DEL_BTN.setVisible(false);
        NOTICE_TITLE.setText("공지사항");
    }//GEN-LAST:event_TITLEMouseClicked

    private void LOGOUTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTMouseClicked
        //로그아웃 버튼 클릭시 로그인 화면으로 이동
        Login l = new Login();
        l.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_LOGOUTMouseClicked

    private void S_MENU4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU4MouseEntered
        // 메뉴 4번 마우스 호버시
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.GRAY);
        jLabel5.setForeground(Color.white);
    }//GEN-LAST:event_S_MENU4MouseEntered

    private void S_MENU4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU4MouseExited
        // 메뉴 4번 마우스 밖으로
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.white);
        jLabel5.setForeground(Color.black);
    }//GEN-LAST:event_S_MENU4MouseExited

    private void S_MENU3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU3MouseEntered
        // 메뉴 3번 마우스 호버시
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.GRAY);
        jLabel4.setForeground(Color.white);
    }//GEN-LAST:event_S_MENU3MouseEntered

    private void S_MENU3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU3MouseExited
        // 메뉴 3번 마우스 밖으로
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.white);
        jLabel4.setForeground(Color.black);
    }//GEN-LAST:event_S_MENU3MouseExited

    private void S_MENU2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU2MouseEntered
        // 메뉴 2번 마우스 호버시
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.GRAY);
        jLabel1.setForeground(Color.white);
    }//GEN-LAST:event_S_MENU2MouseEntered

    private void S_MENU2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU2MouseExited
        // 메뉴 2번 마우스 밖으로
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.white);
        jLabel1.setForeground(Color.black);
    }//GEN-LAST:event_S_MENU2MouseExited

    private void S_MENU1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU1MouseEntered
        // 메뉴 1번 마우스 호버시
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.GRAY);
        jLabel2.setForeground(Color.white);
    }//GEN-LAST:event_S_MENU1MouseEntered

    private void S_MENU1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU1MouseExited
        // 메뉴 1번 마우스 밖으로
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.white);
        jLabel2.setForeground(Color.black);
    }//GEN-LAST:event_S_MENU1MouseExited

    private void LOGOUTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTMouseEntered
        // 로그아웃 호버 시 색 변경
        LOGOUT.setForeground(Color.white);
    }//GEN-LAST:event_LOGOUTMouseEntered

    private void LOGOUTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTMouseExited
        // 로그아웃 마우스 바깥으로
        LOGOUT.setForeground(Color.black);
    }//GEN-LAST:event_LOGOUTMouseExited

    private void TITLEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TITLEMouseEntered
        // 타이틀 호버시 색 변경
        TITLE.setForeground(Color.white);
    }//GEN-LAST:event_TITLEMouseEntered

    private void TITLEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TITLEMouseExited
        // 타이틀 마우스 바깥으로
        TITLE.setForeground(Color.black);
    }//GEN-LAST:event_TITLEMouseExited

    private void NOTICE_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NOTICE_LMouseClicked
        // 메뉴에 공지사항 클릭시 공지사항 내용 출력
        // 컨트롤러에 있는 공지사항 출력 함수 사용
        NOTICE_INPUT_BTN.setVisible(false);
        NOTICE_CHANGE_BTN.setVisible(false);
        NOTICE_DEL_BTN.setVisible(false);
        NOTICE_TITLE.setText("공지사항");
    }//GEN-LAST:event_NOTICE_LMouseClicked

    private void S_MENU4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU4MouseClicked
        // 게시판 메뉴 선택시
        // 컨트롤러에 있는 공지사항 목록 출력 함수 사용
        panelClear();
        S_NOTICE_P.setVisible(true);
        NOTICE_INPUT_BTN.setVisible(false);
        NOTICE_CHANGE_BTN.setVisible(false);
        NOTICE_DEL_BTN.setVisible(false);
        NOTICE_TITLE.setText("공지사항");
    }//GEN-LAST:event_S_MENU4MouseClicked

    private void S_MENU3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU3MouseClicked
        // 마이페이지 메뉴 선택 시
        panelClear();
        // 현재 로그인 한 사용자의 정보를 채워준다.
        MemberManage_controller mc = new MemberManage_controller(this);
        mc.UserInfo();
        S_MYPAGE_P.setVisible(true);
        // 현재 로그인 한 사용자의 정보를 채워준다.
    }//GEN-LAST:event_S_MENU3MouseClicked

    private void S_MENU2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU2MouseClicked
        // 예약 조회 패널로 이동
        panelClear();
        S_INQUIRY_P.setVisible(true);
        INPUT_TEAM.setVisible(false);
        // 컨트롤러에 있는 예약 조회 함수로 테이블 값 채우기
        UseLab_controller ulcontroll = new UseLab_controller(this);
        ulcontroll.showReser();
    }//GEN-LAST:event_S_MENU2MouseClicked

    private void S_MENU1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU1MouseClicked
        // 실습실 예약 패널로 이동
        panelClear();
        LAB_915.setSelected(true);
        S_RESERVATION_P.setVisible(true);
        SELECT_RE_INFO.setVisible(true);
        INPUT_TEAM.setVisible(false);
        CALENDAR_P.setVisible(false);
        SET_DATE_L.setText("선택하기");
        TEAM_CHECK.setSelected(false);
        SEAT_P.setVisible(false);
    }//GEN-LAST:event_S_MENU1MouseClicked

    private void NOTICE_INQUIRY_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NOTICE_INQUIRY_LMouseClicked
        // 문의하기 클릭
        // 문의 내역 출력
        NOTICE_TITLE.setText("신고 및 문의");
        NOTICE_INPUT_BTN.setVisible(true);
        NOTICE_CHANGE_BTN.setVisible(true);
        NOTICE_DEL_BTN.setVisible(true);
    }//GEN-LAST:event_NOTICE_INQUIRY_LMouseClicked

    private void NOTICE_CHECK_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOTICE_CHECK_BTNActionPerformed
        // 게시물 확인하기
        NOTICE_INFO.setVisible(true);
    }//GEN-LAST:event_NOTICE_CHECK_BTNActionPerformed

    private void EXIT_INQUIRY_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXIT_INQUIRY_BTNActionPerformed
        // 문의하기 다이어로그 닫기
        INQUIRY_DIALOG.dispose();
    }//GEN-LAST:event_EXIT_INQUIRY_BTNActionPerformed

    private void INFO_DEL_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INFO_DEL_BTNActionPerformed
        // 탈퇴하기 버튼 클릭
        MemberManage_controller mc = new MemberManage_controller(this);
        mc.DeleteUser();    
    }//GEN-LAST:event_INFO_DEL_BTNActionPerformed

    private void NOTICE_DEL_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOTICE_DEL_BTNActionPerformed
        // 문의 삭제하기
    }//GEN-LAST:event_NOTICE_DEL_BTNActionPerformed

    private void NOTICE_INPUT_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOTICE_INPUT_BTNActionPerformed
        // 문의사항 등록 버튼 클릭 시
        INQUIRY_DIALOG.setVisible(true);
        INPUT_INQUIRY_BTN.setVisible(true);
        CHANGE_INQUIRY_BTN.setVisible(false);
    }//GEN-LAST:event_NOTICE_INPUT_BTNActionPerformed

    private void NOTICE_CHANGE_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOTICE_CHANGE_BTNActionPerformed
        // 수정 버튼 시간 남으면 구현
    }//GEN-LAST:event_NOTICE_CHANGE_BTNActionPerformed

    private void TEAM_CHECKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEAM_CHECKActionPerformed
        // 실습실 예약 패널에서 조별 학습인지 체크하는 체크박스
        if(TEAM_CHECK.isSelected()){ // 팀 학습을 선택할 시
            INPUT_TEAM.setVisible(true);
        }else if(!TEAM_CHECK.isSelected()){ //팀 학습을 선택하지 않았을시
            INPUT_TEAM.setVisible(false);
        }
    }//GEN-LAST:event_TEAM_CHECKActionPerformed

    private void SET_DATE_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SET_DATE_LMouseClicked
        // 날짜 선택하기 라벨 클릭 시간에 맞는 날짜 출력
        CALENDAR_P.setVisible(true);
        
        Calendar getdate = Calendar.getInstance();
        
        YEAR_L.setText(Integer.toString(getdate.get(Calendar.YEAR)));
        MONTH_L.setText(Integer.toString(getdate.get(Calendar.MONTH)+1));
        DATE_P.setVisible(false);
        DATE_P.removeAll();
        DATE_P.setVisible(true);
        getCalendar();
              
    }//GEN-LAST:event_SET_DATE_LMouseClicked

    private void LEFT_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LEFT_LMouseClicked
        // 달력 이전 달 클릭
        int month = Integer.parseInt(MONTH_L.getText())-1;
        if(month == 0){
            YEAR_L.setText(Integer.toString(Integer.parseInt(YEAR_L.getText())-1));
            month = 12;
        }
        MONTH_L.setText(Integer.toString(month));
        DATE_P.setVisible(false);
        DATE_P.removeAll();
        DATE_P.setVisible(true);
        getCalendar();
    }//GEN-LAST:event_LEFT_LMouseClicked

    private void RIGHT_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RIGHT_LMouseClicked
        // 달력 다음 달 클릭
        int month = Integer.parseInt(MONTH_L.getText())+1;
        if(month == 13){
            YEAR_L.setText(Integer.toString(Integer.parseInt(YEAR_L.getText())+1));
            month = 1;
        }
        MONTH_L.setText(Integer.toString(month));
        DATE_P.setVisible(false);
        DATE_P.removeAll();
        DATE_P.setVisible(true);
        getCalendar();
    }//GEN-LAST:event_RIGHT_LMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // 공지사항 닫기
        NOTICE_INFO.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void INFO_CHANGE_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INFO_CHANGE_BTNActionPerformed
         //회원정보 변경 버튼 선택시
        MemberManage_controller mc = new MemberManage_controller(this);
        mc.ChangeInfo();
    }//GEN-LAST:event_INFO_CHANGE_BTNActionPerformed

    private void DELETE_RE_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETE_RE_BTNActionPerformed
        //예약 취소 버튼 선택 시
    }//GEN-LAST:event_DELETE_RE_BTNActionPerformed

    private void SEARCH_CUR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCH_CUR_BTNActionPerformed
        //조회하기 버튼 선택 시
        //날짜와 강의실 선택시 가능한 시간 출력
        Font font = new Font("굴림", Font.BOLD, 15);
        SEAT_P.removeAll();
        ReserLab_controller rc = new ReserLab_controller(this);
        ArrayList<Integer> list = rc.SearchPossibleSeat();
        JLabel seat;
        
        for(int i = 0; i<40; i++){
            seat = new JLabel(Integer.toString(i+1), JLabel.CENTER);
            seat.setFont(font);
            if(list.get(i) == 1)
                SEAT_P.add(seat).setForeground(Color.GRAY);
            else
                SEAT_P.add(seat).setForeground(Color.BLACK);
        }
        SEAT_P.setVisible(true);
    }//GEN-LAST:event_SEARCH_CUR_BTNActionPerformed
    
    public void getCalendar(){ // 달력을 받아오는 함수
        JLabel day;
        Calendar getdate = Calendar.getInstance();

        getdate.set(Integer.parseInt(YEAR_L.getText()), Integer.parseInt(MONTH_L.getText())-1, 1);
        
        int firstday = getdate.get(Calendar.DAY_OF_WEEK);
        int lastday = getdate.getActualMaximum(Calendar.DAY_OF_MONTH);
        
        for(int i=0; i < firstday-1; i++){
            DATE_P.add(new JLabel(" "),JLabel.CENTER);
        }
        for(int i =  0 ; i <= lastday-1; i++) {
            day = new JLabel(Integer.toString(i+1),JLabel.CENTER);
            switch ((firstday+i)%7) {
                case 0:
                    DATE_P.add(day).setForeground(Color.blue);
                    break;
                case 1:
                    DATE_P.add(day).setForeground(Color.red);
                    break;
                default:
                    DATE_P.add(day);
                    break;
            }
            day.addMouseListener(new MyMouseListener());
            day.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        }
    }
    
    class MyMouseListener implements MouseListener{
    
        @Override
        public void mouseClicked(MouseEvent e) {
            JLabel l = (JLabel) e.getSource();
            SET_DATE_L.setText(YEAR_L.getText() + "-" + MONTH_L.getText() + "-" + l.getText());
            CALENDAR_P.setVisible(false);
        }

        @Override
        public void mousePressed(MouseEvent e) {
          
        }

        @Override
        public void mouseReleased(MouseEvent e) {
          
        }

        @Override
        public void mouseEntered(MouseEvent e) {
        }

        @Override
        public void mouseExited(MouseEvent e) {
            
        }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CALENDAR_P;
    public javax.swing.JTextField CHANGE_EMAIL;
    private javax.swing.JButton CHANGE_INQUIRY_BTN;
    public javax.swing.JTextField CHANGE_NAME;
    public javax.swing.JTextField CHANGE_NUMBER;
    public javax.swing.JTextField CHANGE_PHONE;
    public javax.swing.JPasswordField CHANGE_PW;
    public javax.swing.JPanel DATE_P;
    private javax.swing.JButton DELETE_RE_BTN;
    private javax.swing.JButton EXIT_INQUIRY_BTN;
    private javax.swing.JButton INFO_CHANGE_BTN;
    private javax.swing.JButton INFO_DEL_BTN;
    private javax.swing.JButton INPUT_INQUIRY_BTN;
    public javax.swing.JTextArea INPUT_INQUIRY_CONTENT1;
    public javax.swing.JTextField INPUT_INQUIRY_TITLE1;
    private javax.swing.JPanel INPUT_TEAM;
    private javax.swing.JDialog INQUIRY_DIALOG;
    private javax.swing.ButtonGroup INQUIRY_GROUP;
    private javax.swing.JLabel INQUIRY_L;
    private javax.swing.JPanel INQUIRY_P;
    private javax.swing.JRadioButton INQUIRY_RADIO;
    private javax.swing.JLabel INQUIRY_TITLE;
    private javax.swing.JRadioButton LAB_911;
    private javax.swing.JRadioButton LAB_915;
    private javax.swing.JRadioButton LAB_916;
    private javax.swing.JRadioButton LAB_918;
    private javax.swing.JLabel LEFT_L;
    private javax.swing.JLabel LOGOUT;
    private javax.swing.JPanel MAIN_P;
    public javax.swing.JLabel MONTH_L;
    private javax.swing.JButton NOTICE_CHANGE_BTN;
    private javax.swing.JButton NOTICE_CHECK_BTN;
    private javax.swing.JButton NOTICE_DEL_BTN;
    private javax.swing.JDialog NOTICE_INFO;
    private javax.swing.JButton NOTICE_INPUT_BTN;
    private javax.swing.JLabel NOTICE_INQUIRY_L;
    private javax.swing.JLabel NOTICE_L;
    private javax.swing.JTable NOTICE_LIST;
    private javax.swing.JLabel NOTICE_NYM_L;
    private javax.swing.JLabel NOTICE_TITLE;
    private javax.swing.JLabel NOTICE_WRITER_L;
    public javax.swing.JPasswordField NOW_PW;
    public javax.swing.JRadioButton REPORT_RADIO;
    public javax.swing.JTable RESERVATION_TABLE;
    private javax.swing.JLabel RIGHT_L;
    private javax.swing.JButton SEARCH_CUR_BTN;
    public javax.swing.JTextField SEAT_F;
    private javax.swing.JPanel SEAT_P;
    private javax.swing.JPanel SELECT_RE_INFO;
    public javax.swing.JLabel SET_DATE_L;
    public javax.swing.JLabel STU_NUM;
    private javax.swing.JComboBox<String> STU_RESER_ETIME;
    private javax.swing.JComboBox<String> STU_RESER_STIME;
    private javax.swing.JPanel S_INQUIRY_P;
    private javax.swing.JPanel S_MENU1;
    private javax.swing.JPanel S_MENU2;
    private javax.swing.JPanel S_MENU3;
    private javax.swing.JPanel S_MENU4;
    private javax.swing.JPanel S_MENU_P;
    private javax.swing.JPanel S_MYPAGE_P;
    private javax.swing.JPanel S_MY_MENU_P;
    private javax.swing.JPanel S_NOTICE_M_P;
    private javax.swing.JPanel S_NOTICE_P;
    private javax.swing.JPanel S_RESERVATION_P;
    private javax.swing.JPanel S_RESER_MENU_P;
    private javax.swing.JTextField TEAM_1;
    private javax.swing.JTextField TEAM_2;
    private javax.swing.JTextField TEAM_3;
    public javax.swing.JCheckBox TEAM_CHECK;
    public javax.swing.JTextField TEAM_SEAT1_F;
    public javax.swing.JTextField TEAM_SEAT2_F;
    private javax.swing.JTextField TEAM_SEAT3_F;
    private javax.swing.JTextArea TEXT_F;
    private javax.swing.JLabel TITLE;
    private javax.swing.JTextField TITLE_F;
    private javax.swing.JPanel TITLE_P;
    private javax.swing.JPanel UNDER_P;
    public javax.swing.JLabel YEAR_L;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}