/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.Arrays;
import javax.swing.JPanel;

/**
 *
 * @author 20183150 김부성
 * 클래스 사용 용도 : 학생 화면 제작 클래스
 */
public class Student_Main extends javax.swing.JFrame {

    /**
     * Creates new form Student_Main
     */
    public Student_Main() {
        initComponents();
        panelClear();
        S_NOTICE_P.setVisible(true); //초기 메인 화면 출력
    }
    
    public void panelClear(){ // 모든 패널을 지우는 함수
        S_NOTICE_P.setVisible(false);
        S_WRITE.setVisible(false);
        S_MYPAGE_P.setVisible(false);
        S_INQUIRY_P.setVisible(false);
        S_RESERVATION_P.setVisible(false);
    }
    
    public String getChangeName(){ //변경할 이름
        return CHANGE_NAME.getText();
    }
    
    public String getChangeEmail(){ //변경할 이메일
        return CHANGE_EMAIL.getText();
    }
    
    public String getChangePhone(){ //변경할 전화번호
        return CHANGE_PHONE.getText();
    }
    
    public String getNowPw(){ // 현재 비밀번호
        return Arrays.toString(NOW_PW.getPassword());
    }
    
    public String getChangePw(){ //변경할 비밀번호
        return Arrays.toString(CHANGE_PW.getPassword());
    }
    
    public String getLabNum(){ // 예약 강의실 선택 값 받아오는 함수
        String lab = null;
        if(LAB_915.isSelected())
            lab = LAB_915.getText();
        else if(LAB_916.isSelected())
            lab = LAB_916.getText();
        else if(LAB_918.isSelected())
            lab = LAB_918.getText();
        else if(LAB_911.isSelected())
            lab = LAB_911.getText();
        return lab;
    }
    
    public String getStartTime(){ // 예약 시작 시간 받기
        return START_TIME.getSelectedItem().toString();
    }
    
    public String getEndTime(){ // 예약 종료 시간 받기
        return END_TIME.getSelectedItem().toString();
    }
    
    public String getYear(){ //예약 년도
        return YEAR.getSelectedItem().toString();
    }
    
    public String getMonth(){ //예약 월
        return MONTH.getSelectedItem().toString();
    }
    
    public String getDate(){ //예약 일
        return DATE.getSelectedItem().toString();
    }
    
    public void setaddActionListener(ActionListener listener) { //버튼 리스너 함수
        CHANGE_BTN.addActionListener(listener); // 회원정보를 변경하는 버튼
        CHANGE_RE_BTN.addActionListener(listener); // 예약정보 수정 버튼
        DELETE_RE_BTN.addActionListener(listener); // 예약정보 삭제 버튼
        SELECT_DATE_BTN.addActionListener(listener); // 예약정보 선택 버튼
        FINAL_SELECT_RE.addActionListener(listener); //예약 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        UNDER_P = new javax.swing.JPanel();
        MAIN_P = new javax.swing.JPanel();
        S_MENU_P = new javax.swing.JPanel();
        S_MENU2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        S_MENU3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        S_MENU4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        S_MENU1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        S_MYPAGE_P = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CHANGE_NUMBER = new javax.swing.JTextField();
        CHANGE_NAME = new javax.swing.JTextField();
        CHANGE_EMAIL = new javax.swing.JTextField();
        CHANGE_PHONE = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        NOW_PW = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        CHANGE_PW = new javax.swing.JPasswordField();
        CHANGE_BTN = new javax.swing.JButton();
        S_NOTICE_P = new javax.swing.JPanel();
        S_NOTICE_M_P = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        NOTICE_L = new javax.swing.JLabel();
        Declaration_L = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        NOTICE_LIST = new javax.swing.JTable();
        NOTICE_TITLE = new javax.swing.JLabel();
        S_WRITE = new javax.swing.JLabel();
        S_CHANGE = new javax.swing.JLabel();
        S_DELETE = new javax.swing.JLabel();
        S_RESERVATION_P = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        SELECT_RE_INFO = new javax.swing.JPanel();
        LAB_915 = new javax.swing.JRadioButton();
        LAB_916 = new javax.swing.JRadioButton();
        LAB_918 = new javax.swing.JRadioButton();
        LAB_911 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        START_TIME = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        END_TIME = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        YEAR = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        MONTH = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        DATE = new javax.swing.JComboBox<>();
        SELECT_DATE_BTN = new javax.swing.JButton();
        SELECT_SEAT_P = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        FINAL_SELECT_RE = new javax.swing.JButton();
        jLabel71 = new javax.swing.JLabel();
        S_INQUIRY_P = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        INQUIRY_L = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        RESERVATION_TABLE = new javax.swing.JTable();
        CHANGE_RE_BTN = new javax.swing.JButton();
        DELETE_RE_BTN = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        TITLE_P = new javax.swing.JPanel();
        TITLE = new javax.swing.JLabel();
        LOGOUT = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SNAME = new javax.swing.JLabel();
        STU_NUM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("실습실 관리 시스템");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UNDER_P.setMinimumSize(new java.awt.Dimension(814, 590));
        UNDER_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MAIN_P.setBackground(new java.awt.Color(255, 255, 255));
        MAIN_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        S_MENU_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        S_MENU2.setBackground(new java.awt.Color(255, 255, 255));
        S_MENU2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        S_MENU2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        S_MENU2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        S_MENU2.setPreferredSize(new java.awt.Dimension(204, 3));
        S_MENU2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S_MENU2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                S_MENU2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                S_MENU2MouseExited(evt);
            }
        });
        S_MENU2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("예약 내역 조회");
        S_MENU2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 34));

        S_MENU_P.add(S_MENU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 0, 204, 34));

        S_MENU3.setBackground(new java.awt.Color(255, 255, 255));
        S_MENU3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        S_MENU3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        S_MENU3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S_MENU3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                S_MENU3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                S_MENU3MouseExited(evt);
            }
        });
        S_MENU3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("마이페이지");
        S_MENU3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 34));

        S_MENU_P.add(S_MENU3, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 0, 204, 34));

        S_MENU4.setBackground(new java.awt.Color(255, 255, 255));
        S_MENU4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        S_MENU4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        S_MENU4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S_MENU4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                S_MENU4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                S_MENU4MouseExited(evt);
            }
        });
        S_MENU4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("게시판");
        S_MENU4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 34));

        S_MENU_P.add(S_MENU4, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 0, 204, 34));

        S_MENU1.setBackground(new java.awt.Color(255, 255, 255));
        S_MENU1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        S_MENU1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        S_MENU1.setPreferredSize(new java.awt.Dimension(204, 34));
        S_MENU1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S_MENU1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                S_MENU1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                S_MENU1MouseExited(evt);
            }
        });
        S_MENU1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("실습실 예약");
        S_MENU1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 34));

        S_MENU_P.add(S_MENU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 204, 34));

        MAIN_P.add(S_MENU_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        S_MYPAGE_P.setBackground(new java.awt.Color(255, 255, 255));
        S_MYPAGE_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(150, 426));

        jLabel7.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel7.setText("MENU");

        jLabel8.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        jLabel8.setText("개인 정보 수정");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel7)
                .addGap(17, 17, 17)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        S_MYPAGE_P.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        jLabel10.setText("학번");
        S_MYPAGE_P.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jLabel11.setText("이름");
        S_MYPAGE_P.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        jLabel12.setText("이메일");
        S_MYPAGE_P.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        jLabel13.setText("전화번호");
        S_MYPAGE_P.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        jLabel14.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel14.setText("개인 정보 수정");
        S_MYPAGE_P.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        CHANGE_NUMBER.setEditable(false);
        S_MYPAGE_P.add(CHANGE_NUMBER, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 100, -1));
        S_MYPAGE_P.add(CHANGE_NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 100, -1));
        S_MYPAGE_P.add(CHANGE_EMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 180, -1));
        S_MYPAGE_P.add(CHANGE_PHONE, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 180, -1));

        jLabel15.setText("현재 비밀번호");
        S_MYPAGE_P.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, -1, -1));
        S_MYPAGE_P.add(NOW_PW, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 150, -1));

        jLabel16.setText("변경된 비밀번호");
        S_MYPAGE_P.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, -1, -1));
        S_MYPAGE_P.add(CHANGE_PW, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 150, -1));

        CHANGE_BTN.setText("변경하기");
        S_MYPAGE_P.add(CHANGE_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, -1, -1));

        MAIN_P.add(S_MYPAGE_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 814, 426));

        S_NOTICE_P.setBackground(new java.awt.Color(255, 255, 255));
        S_NOTICE_P.setVerifyInputWhenFocusTarget(false);
        S_NOTICE_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        S_NOTICE_M_P.setPreferredSize(new java.awt.Dimension(100, 426));

        jLabel6.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel6.setText("MENU");

        NOTICE_L.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        NOTICE_L.setText("공지사항");
        NOTICE_L.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NOTICE_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NOTICE_LMouseClicked(evt);
            }
        });

        Declaration_L.setText("신고 및 문의");
        Declaration_L.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Declaration_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Declaration_LMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout S_NOTICE_M_PLayout = new javax.swing.GroupLayout(S_NOTICE_M_P);
        S_NOTICE_M_P.setLayout(S_NOTICE_M_PLayout);
        S_NOTICE_M_PLayout.setHorizontalGroup(
            S_NOTICE_M_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(S_NOTICE_M_PLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(S_NOTICE_M_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(NOTICE_L)
                    .addComponent(Declaration_L))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(S_NOTICE_M_PLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        S_NOTICE_M_PLayout.setVerticalGroup(
            S_NOTICE_M_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(S_NOTICE_M_PLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NOTICE_L)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Declaration_L)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        S_NOTICE_P.add(S_NOTICE_M_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 426));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setPreferredSize(new java.awt.Dimension(454, 0));

        NOTICE_LIST.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "날짜", "제목", "작성자", "비고"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        NOTICE_LIST.setGridColor(new java.awt.Color(255, 255, 255));
        NOTICE_LIST.setPreferredSize(new java.awt.Dimension(660, 0));
        NOTICE_LIST.setSelectionBackground(new java.awt.Color(255, 255, 255));
        NOTICE_LIST.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        NOTICE_LIST.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        NOTICE_LIST.setShowGrid(true);
        jScrollPane1.setViewportView(NOTICE_LIST);

        S_NOTICE_P.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 56, 666, 370));

        NOTICE_TITLE.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        NOTICE_TITLE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NOTICE_TITLE.setText("공지사항");
        S_NOTICE_P.add(NOTICE_TITLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 160, -1));

        S_WRITE.setText("글쓰기");
        S_WRITE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        S_WRITE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S_WRITEMouseClicked(evt);
            }
        });
        S_NOTICE_P.add(S_WRITE, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, -1));

        S_CHANGE.setText("수정");
        S_CHANGE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        S_CHANGE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S_CHANGEMouseClicked(evt);
            }
        });
        S_NOTICE_P.add(S_CHANGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));

        S_DELETE.setText("삭제");
        S_DELETE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        S_DELETE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S_DELETEMouseClicked(evt);
            }
        });
        S_NOTICE_P.add(S_DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, -1, -1));

        MAIN_P.add(S_NOTICE_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 814, 426));

        S_RESERVATION_P.setBackground(new java.awt.Color(255, 255, 255));
        S_RESERVATION_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel19.setText("MENU");

        jLabel20.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        jLabel20.setText("실습실 예약");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addContainerGap(319, Short.MAX_VALUE))
        );

        S_RESERVATION_P.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 430));

        jLabel21.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel21.setText("실습실 예약");
        S_RESERVATION_P.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        SELECT_RE_INFO.setBackground(new java.awt.Color(255, 255, 255));
        SELECT_RE_INFO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LAB_915.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(LAB_915);
        LAB_915.setText("915호");
        SELECT_RE_INFO.add(LAB_915, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 60, -1));

        LAB_916.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(LAB_916);
        LAB_916.setText("916호");
        SELECT_RE_INFO.add(LAB_916, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 60, -1));

        LAB_918.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(LAB_918);
        LAB_918.setText("918호");
        SELECT_RE_INFO.add(LAB_918, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 60, -1));

        LAB_911.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(LAB_911);
        LAB_911.setText("911호");
        SELECT_RE_INFO.add(LAB_911, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 60, -1));

        jLabel22.setText("시작 시간");
        SELECT_RE_INFO.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, 20));

        START_TIME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 : 00", "2 : 00", "3 : 00", "4 : 00", "5 : 00", "6 : 00", "7 : 00", "8 : 00", "9 : 00", "10 : 00", "11 : 00", "12 : 00", "13 : 00", "14 : 00", "15 : 00", "16 : 00", "17 : 00", "18 : 00", "19 : 00", "20 : 00", "21 : 00", "22 : 00", "23 : 00", "24 : 00" }));
        SELECT_RE_INFO.add(START_TIME, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 100, 20));

        jLabel23.setText("종료시간");
        SELECT_RE_INFO.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, 20));

        END_TIME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 : 00", "2 : 00", "3 : 00", "4 : 00", "5 : 00", "6 : 00", "7 : 00", "8 : 00", "9 : 00", "10 : 00", "11 : 00", "12 : 00", "13 : 00", "14 : 00", "15 : 00", "16 : 00", "17 : 00", "18 : 00", "19 : 00", "20 : 00", "21 : 00", "22 : 00", "23 : 00", "24 : 00" }));
        SELECT_RE_INFO.add(END_TIME, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 100, 20));
        SELECT_RE_INFO.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        jLabel25.setFont(new java.awt.Font("굴림", 0, 15)); // NOI18N
        jLabel25.setText("날짜");
        SELECT_RE_INFO.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        jLabel26.setFont(new java.awt.Font("굴림", 0, 15)); // NOI18N
        jLabel26.setText("강의실");
        SELECT_RE_INFO.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));
        SELECT_RE_INFO.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 92, 480, 0));

        jLabel27.setFont(new java.awt.Font("굴림", 0, 15)); // NOI18N
        jLabel27.setText("시간");
        SELECT_RE_INFO.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));
        SELECT_RE_INFO.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 490, -1));

        jLabel28.setText("년도");
        SELECT_RE_INFO.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        SELECT_RE_INFO.add(YEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 100, -1));

        jLabel29.setText("월");
        SELECT_RE_INFO.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        SELECT_RE_INFO.add(MONTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 100, -1));

        jLabel30.setText("일");
        SELECT_RE_INFO.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        SELECT_RE_INFO.add(DATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 100, -1));

        SELECT_DATE_BTN.setBackground(new java.awt.Color(255, 255, 255));
        SELECT_DATE_BTN.setText("선택");
        SELECT_RE_INFO.add(SELECT_DATE_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 70, -1));

        S_RESERVATION_P.add(SELECT_RE_INFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 75, 664, 350));

        SELECT_SEAT_P.setBackground(new java.awt.Color(255, 255, 255));

        jLabel31.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel31.setText("1");

        jLabel32.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel32.setText("2");

        jLabel33.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel33.setText("3");

        jLabel34.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel34.setText("4");

        jLabel35.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel35.setText("9");

        jLabel36.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel36.setText("10");

        jLabel37.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel37.setText("11");

        jLabel38.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel38.setText("12");

        jLabel39.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel39.setText("17");

        jLabel40.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel40.setText("18");

        jLabel41.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel41.setText("19");

        jLabel42.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel42.setText("20");

        jLabel43.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel43.setText("25");

        jLabel44.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel44.setText("26");

        jLabel45.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel45.setText("27");

        jLabel46.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel46.setText("28");

        jLabel47.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel47.setText("5");

        jLabel48.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel48.setText("6");

        jLabel49.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel49.setText("7");

        jLabel50.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel50.setText("8");

        jLabel52.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel52.setText("14");

        jLabel53.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel53.setText("15");

        jLabel54.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel54.setText("16");

        jLabel55.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel55.setText("13");

        jLabel56.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel56.setText("22");

        jLabel57.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel57.setText("23");

        jLabel58.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel58.setText("24");

        jLabel59.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel59.setText("21");

        jLabel60.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel60.setText("30");

        jLabel61.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel61.setText("31");

        jLabel62.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel62.setText("32");

        jLabel63.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel63.setText("29");

        jLabel64.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel64.setText("38");

        jLabel65.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel65.setText("39");

        jLabel66.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel66.setText("40");

        jLabel67.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel67.setText("37");

        jLabel51.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel51.setText("33");

        jLabel68.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel68.setText("34");

        jLabel69.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel69.setText("35");

        jLabel70.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel70.setText("36");

        FINAL_SELECT_RE.setBackground(new java.awt.Color(255, 255, 255));
        FINAL_SELECT_RE.setText("선택");

        jLabel71.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel71.setText("좌석 배치도");

        javax.swing.GroupLayout SELECT_SEAT_PLayout = new javax.swing.GroupLayout(SELECT_SEAT_P);
        SELECT_SEAT_P.setLayout(SELECT_SEAT_PLayout);
        SELECT_SEAT_PLayout.setHorizontalGroup(
            SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SELECT_SEAT_PLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SELECT_SEAT_PLayout.createSequentialGroup()
                        .addComponent(jLabel51)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel68)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel69)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel70))
                    .addGroup(SELECT_SEAT_PLayout.createSequentialGroup()
                        .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(jLabel39)
                            .addComponent(jLabel35)
                            .addComponent(jLabel31))
                        .addGap(40, 40, 40)
                        .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44)
                            .addComponent(jLabel40)
                            .addComponent(jLabel36)
                            .addComponent(jLabel32))
                        .addGap(40, 40, 40)
                        .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45)
                            .addComponent(jLabel41)
                            .addComponent(jLabel37)
                            .addComponent(jLabel33))
                        .addGap(40, 40, 40)
                        .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46)
                            .addComponent(jLabel38)
                            .addComponent(jLabel42)
                            .addComponent(jLabel34))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SELECT_SEAT_PLayout.createSequentialGroup()
                        .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SELECT_SEAT_PLayout.createSequentialGroup()
                                .addComponent(jLabel59)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel56))
                            .addGroup(SELECT_SEAT_PLayout.createSequentialGroup()
                                .addComponent(jLabel55)
                                .addGap(40, 40, 40)
                                .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel48)
                                    .addComponent(jLabel52)))
                            .addComponent(jLabel47))
                        .addGap(40, 40, 40)
                        .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel53)
                            .addComponent(jLabel49))
                        .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SELECT_SEAT_PLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel58))
                            .addGroup(SELECT_SEAT_PLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel50)
                                    .addComponent(jLabel54)))))
                    .addGroup(SELECT_SEAT_PLayout.createSequentialGroup()
                        .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel63)
                            .addComponent(jLabel67))
                        .addGap(40, 40, 40)
                        .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel60)
                            .addComponent(jLabel64))
                        .addGap(40, 40, 40)
                        .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel61)
                            .addComponent(jLabel65))
                        .addGap(40, 40, 40)
                        .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel66)
                            .addComponent(jLabel62)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SELECT_SEAT_PLayout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FINAL_SELECT_RE, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
            .addGroup(SELECT_SEAT_PLayout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(jLabel71)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SELECT_SEAT_PLayout.setVerticalGroup(
            SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SELECT_SEAT_PLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel71)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(jLabel48)
                    .addComponent(jLabel49)
                    .addComponent(jLabel50))
                .addGap(30, 30, 30)
                .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(jLabel52)
                    .addComponent(jLabel53)
                    .addComponent(jLabel54))
                .addGap(30, 30, 30)
                .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(jLabel56)
                    .addComponent(jLabel57)
                    .addComponent(jLabel58))
                .addGap(30, 30, 30)
                .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63)
                    .addComponent(jLabel60)
                    .addComponent(jLabel61)
                    .addComponent(jLabel62))
                .addGap(18, 18, 18)
                .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel67)
                    .addComponent(jLabel64)
                    .addComponent(jLabel65)
                    .addComponent(jLabel66))
                .addGap(18, 18, 18)
                .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FINAL_SELECT_RE))
                .addGap(36, 36, 36))
            .addGroup(SELECT_SEAT_PLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addGap(30, 30, 30)
                .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38))
                .addGap(30, 30, 30)
                .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42))
                .addGap(30, 30, 30)
                .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jLabel44)
                    .addComponent(jLabel45)
                    .addComponent(jLabel46))
                .addGap(18, 18, 18)
                .addGroup(SELECT_SEAT_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(jLabel68)
                    .addComponent(jLabel69)
                    .addComponent(jLabel70))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        S_RESERVATION_P.add(SELECT_SEAT_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 75, 664, 350));

        MAIN_P.add(S_RESERVATION_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 814, 426));

        S_INQUIRY_P.setBackground(new java.awt.Color(255, 255, 255));
        S_INQUIRY_P.setVerifyInputWhenFocusTarget(false);
        S_INQUIRY_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel17.setText("MENU");

        INQUIRY_L.setFont(new java.awt.Font("굴림", 0, 16)); // NOI18N
        INQUIRY_L.setText("예약 내역 조회");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(INQUIRY_L)
                    .addComponent(jSeparator3)
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(INQUIRY_L)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        S_INQUIRY_P.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, -1));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(664, 320));

        RESERVATION_TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "날짜", "강의실", "시작 시간", "종료 시간"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        RESERVATION_TABLE.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        RESERVATION_TABLE.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(RESERVATION_TABLE);

        S_INQUIRY_P.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 664, 260));

        CHANGE_RE_BTN.setText("수정하기");
        S_INQUIRY_P.add(CHANGE_RE_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, -1, -1));

        DELETE_RE_BTN.setText("취소하기");
        S_INQUIRY_P.add(DELETE_RE_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, -1, -1));

        jLabel18.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel18.setText("예약 내역 조회");
        S_INQUIRY_P.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        MAIN_P.add(S_INQUIRY_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 814, 426));

        UNDER_P.add(MAIN_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, 460));

        TITLE_P.setBackground(new java.awt.Color(0, 204, 255));
        TITLE_P.setMinimumSize(new java.awt.Dimension(810, 122));
        TITLE_P.setPreferredSize(new java.awt.Dimension(814, 128));
        TITLE_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TITLE.setFont(new java.awt.Font("맑은 고딕", 1, 48)); // NOI18N
        TITLE.setForeground(new java.awt.Color(255, 255, 255));
        TITLE.setText("S.M.P");
        TITLE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TITLE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TITLEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TITLEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TITLEMouseExited(evt);
            }
        });
        TITLE_P.add(TITLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 30, -1, -1));

        LOGOUT.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        LOGOUT.setForeground(new java.awt.Color(255, 255, 255));
        LOGOUT.setText("로그아웃");
        LOGOUT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LOGOUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGOUTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LOGOUTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LOGOUTMouseExited(evt);
            }
        });
        TITLE_P.add(LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 102, -1, -1));

        jLabel3.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("님");
        TITLE_P.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 102, -1, -1));

        SNAME.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        SNAME.setForeground(new java.awt.Color(255, 255, 255));
        SNAME.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SNAME.setText("강상혁");
        TITLE_P.add(SNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 102, -1, -1));

        STU_NUM.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        STU_NUM.setForeground(new java.awt.Color(255, 255, 255));
        STU_NUM.setText("20183109");
        TITLE_P.add(STU_NUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 102, -1, -1));

        UNDER_P.add(TITLE_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 814, 130));

        getContentPane().add(UNDER_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TITLEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TITLEMouseClicked
        //타이틀 클릭시 메인 패널로 이동
        S_NOTICE_P.setVisible(true);
    }//GEN-LAST:event_TITLEMouseClicked

    private void LOGOUTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTMouseClicked
        //로그아웃 버튼 클릭시 로그인 화면으로 이동
        Login l = new Login();
        l.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_LOGOUTMouseClicked

    private void S_MENU4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU4MouseEntered
        // 메뉴 4번 마우스 호버시
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.GRAY);
        jLabel5.setForeground(Color.white);
    }//GEN-LAST:event_S_MENU4MouseEntered

    private void S_MENU4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU4MouseExited
        // 메뉴 4번 마우스 밖으로
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.white);
        jLabel5.setForeground(Color.black);
    }//GEN-LAST:event_S_MENU4MouseExited

    private void S_MENU3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU3MouseEntered
        // 메뉴 3번 마우스 호버시
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.GRAY);
        jLabel4.setForeground(Color.white);
    }//GEN-LAST:event_S_MENU3MouseEntered

    private void S_MENU3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU3MouseExited
        // 메뉴 3번 마우스 밖으로
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.white);
        jLabel4.setForeground(Color.black);
    }//GEN-LAST:event_S_MENU3MouseExited

    private void S_MENU2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU2MouseEntered
        // 메뉴 2번 마우스 호버시
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.GRAY);
        jLabel1.setForeground(Color.white);
    }//GEN-LAST:event_S_MENU2MouseEntered

    private void S_MENU2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU2MouseExited
        // 메뉴 2번 마우스 밖으로
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.white);
        jLabel1.setForeground(Color.black);
    }//GEN-LAST:event_S_MENU2MouseExited

    private void S_MENU1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU1MouseEntered
        // 메뉴 1번 마우스 호버시
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.GRAY);
        jLabel2.setForeground(Color.white);
    }//GEN-LAST:event_S_MENU1MouseEntered

    private void S_MENU1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU1MouseExited
        // 메뉴 1번 마우스 밖으로
        JPanel p = (JPanel)evt.getSource();
        p.setBackground(Color.white);
        jLabel2.setForeground(Color.black);
    }//GEN-LAST:event_S_MENU1MouseExited

    private void LOGOUTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTMouseEntered
        // 로그아웃 호버 시 색 변경
        LOGOUT.setForeground(Color.black);
    }//GEN-LAST:event_LOGOUTMouseEntered

    private void LOGOUTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTMouseExited
        // 로그아웃 마우스 바깥으로
        LOGOUT.setForeground(Color.white);
    }//GEN-LAST:event_LOGOUTMouseExited

    private void TITLEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TITLEMouseEntered
        // 타이틀 호버시 색 변경
        TITLE.setForeground(Color.black);
    }//GEN-LAST:event_TITLEMouseEntered

    private void TITLEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TITLEMouseExited
        // 타이틀 마우스 바깥으로
        TITLE.setForeground(Color.white);
    }//GEN-LAST:event_TITLEMouseExited

    private void S_WRITEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_WRITEMouseClicked
        // 글 작성 화면 띄우기
        Write_Post w = new Write_Post();
        w.setVisible(true);
    }//GEN-LAST:event_S_WRITEMouseClicked

    private void S_CHANGEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_CHANGEMouseClicked
        // 글 수정 화면 띄우기(본인 글에 한해서)
        Write_Post w = new Write_Post();
        w.setVisible(true);
    }//GEN-LAST:event_S_CHANGEMouseClicked

    private void S_DELETEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_DELETEMouseClicked
        //리스트에 있는 게시글 삭제(본인 글에 한해서)
        // 컨트롤러에 있는 목록 삭제 함수 사용
    }//GEN-LAST:event_S_DELETEMouseClicked

    private void NOTICE_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NOTICE_LMouseClicked
        // 메뉴에 공지사항 클릭시 공지사항 내용 출력
        // 컨트롤러에 있는 공지사항 출력 함수 사용
        S_WRITE.setVisible(false);
        NOTICE_TITLE.setText("공지사항");
    }//GEN-LAST:event_NOTICE_LMouseClicked

    private void Declaration_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Declaration_LMouseClicked
        // 메뉴에 신고 및 문의 클릭시 신고 및 문의 내용 출력
        // 컨트롤러에 있는 신고 및 문의사항 출력 함수 사용
        S_WRITE.setVisible(true);
        NOTICE_TITLE.setText("신고 및 문의");
    }//GEN-LAST:event_Declaration_LMouseClicked

    private void S_MENU4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU4MouseClicked
        // 게시판 메뉴 선택시
        // 컨트롤러에 있는 공지사항 목록 출력 함수 사용
        panelClear();
        S_NOTICE_P.setVisible(true);
        S_WRITE.setVisible(false);
        NOTICE_TITLE.setText("공지사항");
    }//GEN-LAST:event_S_MENU4MouseClicked

    private void S_MENU3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU3MouseClicked
        // 마이페이지 메뉴 선택 시
        panelClear();
        S_MYPAGE_P.setVisible(true);
        // 현재 로그인 한 사용자의 정보를 채워준다.
    }//GEN-LAST:event_S_MENU3MouseClicked

    private void S_MENU2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU2MouseClicked
        // 예약 조회 패널로 이동
        panelClear();
        S_INQUIRY_P.setVisible(true);
        // 컨트롤러에 있는 예약 조회 함수로 테이블 값 채우기
    }//GEN-LAST:event_S_MENU2MouseClicked

    private void S_MENU1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_MENU1MouseClicked
        // 실습실 예약 패널로 이동
        panelClear();
        LAB_915.setSelected(true);
        S_RESERVATION_P.setVisible(true);
        SELECT_RE_INFO.setVisible(true);
        SELECT_SEAT_P.setVisible(false);
    }//GEN-LAST:event_S_MENU1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CHANGE_BTN;
    private javax.swing.JTextField CHANGE_EMAIL;
    private javax.swing.JTextField CHANGE_NAME;
    private javax.swing.JTextField CHANGE_NUMBER;
    private javax.swing.JTextField CHANGE_PHONE;
    private javax.swing.JPasswordField CHANGE_PW;
    private javax.swing.JButton CHANGE_RE_BTN;
    private javax.swing.JComboBox<String> DATE;
    private javax.swing.JButton DELETE_RE_BTN;
    private javax.swing.JLabel Declaration_L;
    private javax.swing.JComboBox<String> END_TIME;
    private javax.swing.JButton FINAL_SELECT_RE;
    private javax.swing.JLabel INQUIRY_L;
    private javax.swing.JRadioButton LAB_911;
    private javax.swing.JRadioButton LAB_915;
    private javax.swing.JRadioButton LAB_916;
    private javax.swing.JRadioButton LAB_918;
    private javax.swing.JLabel LOGOUT;
    private javax.swing.JPanel MAIN_P;
    private javax.swing.JComboBox<String> MONTH;
    private javax.swing.JLabel NOTICE_L;
    private javax.swing.JTable NOTICE_LIST;
    private javax.swing.JLabel NOTICE_TITLE;
    private javax.swing.JPasswordField NOW_PW;
    private javax.swing.JTable RESERVATION_TABLE;
    private javax.swing.JButton SELECT_DATE_BTN;
    private javax.swing.JPanel SELECT_RE_INFO;
    private javax.swing.JPanel SELECT_SEAT_P;
    private javax.swing.JLabel SNAME;
    private javax.swing.JComboBox<String> START_TIME;
    private javax.swing.JLabel STU_NUM;
    private javax.swing.JLabel S_CHANGE;
    private javax.swing.JLabel S_DELETE;
    private javax.swing.JPanel S_INQUIRY_P;
    private javax.swing.JPanel S_MENU1;
    private javax.swing.JPanel S_MENU2;
    private javax.swing.JPanel S_MENU3;
    private javax.swing.JPanel S_MENU4;
    private javax.swing.JPanel S_MENU_P;
    private javax.swing.JPanel S_MYPAGE_P;
    private javax.swing.JPanel S_NOTICE_M_P;
    private javax.swing.JPanel S_NOTICE_P;
    private javax.swing.JPanel S_RESERVATION_P;
    private javax.swing.JLabel S_WRITE;
    private javax.swing.JLabel TITLE;
    private javax.swing.JPanel TITLE_P;
    private javax.swing.JPanel UNDER_P;
    private javax.swing.JComboBox<String> YEAR;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
